ALTER TABLE "marketplace_publication_events" DROP CONSTRAINT "marketplace_publication_events_status_check";--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" DROP CONSTRAINT "marketplace_publication_requests_action_check";--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" DROP CONSTRAINT "marketplace_publication_requests_platform_action_check";--> statement-breakpoint
ALTER TABLE "marketplace_publication_events" ADD COLUMN "external_media_ids" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" ADD COLUMN "parent_request_id" uuid;--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" ADD COLUMN "source_external_listing_id" text;--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" ADD CONSTRAINT "marketplace_publication_requests_parent_fk" FOREIGN KEY ("tenant_id","parent_request_id") REFERENCES "public"."marketplace_publication_requests"("tenant_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "marketplace_publication_requests_parent_idx" ON "marketplace_publication_requests" USING btree ("tenant_id","parent_request_id");--> statement-breakpoint
ALTER TABLE "marketplace_publication_events" ADD CONSTRAINT "marketplace_publication_events_status_check" CHECK ("marketplace_publication_events"."status" in ('queued', 'processing', 'validation_passed', 'validation_failed', 'draft_created', 'submission_accepted', 'media_uploaded', 'activation_accepted', 'sync_pending', 'published', 'publication_failed', 'deactivated', 'retry_pending', 'reconciliation_required', 'failed'));--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" ADD CONSTRAINT "marketplace_publication_requests_followup_check" CHECK (("marketplace_publication_requests"."action" in ('amazon_validation_preview', 'etsy_create_draft') and "marketplace_publication_requests"."parent_request_id" is null and "marketplace_publication_requests"."source_external_listing_id" is null) or ("marketplace_publication_requests"."action" = 'amazon_submit' and "marketplace_publication_requests"."parent_request_id" is not null and "marketplace_publication_requests"."source_external_listing_id" is null) or ("marketplace_publication_requests"."action" = 'etsy_activate' and "marketplace_publication_requests"."parent_request_id" is not null and "marketplace_publication_requests"."source_external_listing_id" is not null));--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" ADD CONSTRAINT "marketplace_publication_requests_action_check" CHECK ("marketplace_publication_requests"."action" in ('amazon_validation_preview', 'amazon_submit', 'etsy_create_draft', 'etsy_activate'));--> statement-breakpoint
ALTER TABLE "marketplace_publication_requests" ADD CONSTRAINT "marketplace_publication_requests_platform_action_check" CHECK (("marketplace_publication_requests"."platform" = 'amazon' and "marketplace_publication_requests"."action" in ('amazon_validation_preview', 'amazon_submit')) or ("marketplace_publication_requests"."platform" = 'etsy' and "marketplace_publication_requests"."action" in ('etsy_create_draft', 'etsy_activate')));