import type {
  AdvertisingEntityLevel,
  AdvertisingProvider,
  CustomerRecommendationAction,
  CustomerSignalConsent,
  CustomerSignalSentiment,
  CustomerSignalSource,
  VocSourceWeight,
} from "@yummyai/contracts/customer-intelligence";
import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { skus } from "./catalog.js";
import { organizations, users } from "./identity.js";
import { listings } from "./listing.js";
import { marketplaceAccounts } from "./marketplace.js";

export const advertisingReports = pgTable("advertising_reports", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  provider: text("provider").$type<AdvertisingProvider>().notNull(),
  accountId: uuid("account_id"),
  externalReportId: text("external_report_id").notNull(),
  scopeKey: text("scope_key").notNull(),
  periodStart: timestamp("period_start", { mode: "date", withTimezone: true }).notNull(),
  periodEnd: timestamp("period_end", { mode: "date", withTimezone: true }).notNull(),
  attributionWindowDays: integer("attribution_window_days").notNull(),
  sourceCurrency: text("source_currency").notNull(),
  observedAt: timestamp("observed_at", { mode: "date", withTimezone: true }).notNull(),
  checksum: text("checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  recordedBy: uuid("recorded_by").references(() => users.id, { onDelete: "set null" }),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("advertising_reports_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("advertising_reports_provider_check", sql`${table.provider} in ('amazon_ads','etsy_ads','manual')`),
  check("advertising_reports_period_check", sql`${table.periodEnd} >= ${table.periodStart} and ${table.observedAt} >= ${table.periodEnd}`),
  check("advertising_reports_attribution_check", sql`${table.attributionWindowDays} between 0 and 365`),
  check("advertising_reports_currency_check", sql`${table.sourceCurrency} ~ '^[A-Z]{3}$'`),
  check("advertising_reports_checksum_check", sql`${table.checksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({
    columns: [table.tenantId, table.accountId],
    foreignColumns: [marketplaceAccounts.tenantId, marketplaceAccounts.id],
    name: "advertising_reports_account_fk",
  }).onDelete("restrict"),
  unique("advertising_reports_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("advertising_reports_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  uniqueIndex("advertising_reports_provider_external_unique").on(table.tenantId, table.provider, table.externalReportId),
  index("advertising_reports_period_idx").on(table.tenantId, table.periodEnd, table.recordedAt),
]);

export const advertisingMetricLines = pgTable("advertising_metric_lines", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  reportId: uuid("report_id").notNull(),
  lineKey: text("line_key").notNull(),
  entityLevel: text("entity_level").$type<AdvertisingEntityLevel>().notNull(),
  externalCampaignId: text("external_campaign_id").notNull(),
  externalAdGroupId: text("external_ad_group_id"),
  normalizedTerm: text("normalized_term"),
  identityRedacted: boolean("identity_redacted").notNull(),
  listingId: uuid("listing_id"),
  skuId: uuid("sku_id"),
  impressions: bigint("impressions", { mode: "number" }).notNull(),
  clicks: bigint("clicks", { mode: "number" }).notNull(),
  orders: bigint("orders", { mode: "number" }).notNull(),
  spendMinor: bigint("spend_minor", { mode: "number" }).notNull(),
  salesMinor: bigint("sales_minor", { mode: "number" }).notNull(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("advertising_metric_lines_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("advertising_metric_lines_level_check", sql`${table.entityLevel} in ('campaign','ad_group','keyword','search_term')`),
  check("advertising_metric_lines_redacted_check", sql`${table.identityRedacted} = true`),
  check("advertising_metric_lines_values_check", sql`${table.impressions} >= 0 and ${table.clicks} >= 0 and ${table.orders} >= 0 and ${table.spendMinor} >= 0 and ${table.salesMinor} >= 0 and ${table.clicks} <= ${table.impressions} and ${table.orders} <= ${table.clicks}`),
  check("advertising_metric_lines_term_check", sql`(${table.entityLevel} in ('keyword','search_term')) = (${table.normalizedTerm} is not null)`),
  foreignKey({ columns: [table.tenantId, table.reportId], foreignColumns: [advertisingReports.tenantId, advertisingReports.id], name: "advertising_metric_lines_report_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.listingId], foreignColumns: [listings.tenantId, listings.id], name: "advertising_metric_lines_listing_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.skuId], foreignColumns: [skus.tenantId, skus.id], name: "advertising_metric_lines_sku_fk" }).onDelete("restrict"),
  unique("advertising_metric_lines_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("advertising_metric_lines_report_key_unique").on(table.tenantId, table.reportId, table.lineKey),
  index("advertising_metric_lines_term_idx").on(table.tenantId, table.entityLevel, table.normalizedTerm),
]);

export const customerSignalFacts = pgTable("customer_signal_facts", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  sourceType: text("source_type").$type<CustomerSignalSource>().notNull(),
  sourceId: uuid("source_id").notNull(),
  themeCode: text("theme_code").notNull(),
  sentiment: text("sentiment").$type<CustomerSignalSentiment>().notNull(),
  occurrenceCount: integer("occurrence_count").notNull(),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).notNull(),
  consentBasis: text("consent_basis").$type<CustomerSignalConsent>().notNull(),
  identityRedacted: boolean("identity_redacted").notNull(),
  excerptChecksum: text("excerpt_checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  recordedBy: uuid("recorded_by").references(() => users.id, { onDelete: "set null" }),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("customer_signal_facts_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("customer_signal_facts_source_check", sql`${table.sourceType} in ('review','return_reason','support_contact','quality_defect','keyword')`),
  check("customer_signal_facts_sentiment_check", sql`${table.sentiment} in ('negative','neutral','positive','mixed')`),
  check("customer_signal_facts_consent_check", sql`${table.consentBasis} in ('public_page','marketplace_authorization','customer_support','internal_quality','advertising_authorization')`),
  check("customer_signal_facts_redacted_check", sql`${table.identityRedacted} = true`),
  check("customer_signal_facts_occurrence_check", sql`${table.occurrenceCount} between 1 and 1000000`),
  check("customer_signal_facts_theme_check", sql`${table.themeCode} ~ '^[A-Z0-9][A-Z0-9._-]*$'`),
  check("customer_signal_facts_checksum_check", sql`${table.excerptChecksum} ~ '^[0-9a-f]{64}$'`),
  unique("customer_signal_facts_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("customer_signal_facts_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("customer_signal_facts_window_idx").on(table.tenantId, table.occurredAt, table.sourceType),
  index("customer_signal_facts_theme_idx").on(table.tenantId, table.themeCode, table.occurredAt),
]);

export const vocDefinitions = pgTable("voc_definitions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  currentVersion: integer("current_version").default(1).notNull(),
  status: text("status").default("active").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("voc_definitions_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("voc_definitions_version_check", sql`${table.currentVersion} > 0`),
  check("voc_definitions_status_check", sql`${table.status} in ('active','inactive')`),
  unique("voc_definitions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("voc_definitions_name_unique").on(table.tenantId, table.name),
]);

export const vocDefinitionVersions = pgTable("voc_definition_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  definitionId: uuid("definition_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  sourceWeights: jsonb("source_weights").$type<VocSourceWeight[]>().notNull(),
  minimumOccurrences: integer("minimum_occurrences").notNull(),
  reasonCode: text("reason_code").notNull(),
  checksum: text("checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("voc_definition_versions_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("voc_definition_versions_number_check", sql`${table.versionNumber} > 0`),
  check("voc_definition_versions_occurrence_check", sql`${table.minimumOccurrences} between 1 and 1000000`),
  check("voc_definition_versions_checksum_check", sql`${table.checksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({ columns: [table.tenantId, table.definitionId], foreignColumns: [vocDefinitions.tenantId, vocDefinitions.id], name: "voc_definition_versions_definition_fk" }).onDelete("restrict"),
  unique("voc_definition_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("voc_definition_versions_number_unique").on(table.tenantId, table.definitionId, table.versionNumber),
  uniqueIndex("voc_definition_versions_idempotency_unique").on(table.tenantId, table.idempotencyKey),
]);

export const vocAnalysisRuns = pgTable("voc_analysis_runs", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  definitionId: uuid("definition_id").notNull(),
  definitionVersionId: uuid("definition_version_id").notNull(),
  definitionVersion: integer("definition_version").notNull(),
  status: text("status").notNull(),
  windowStart: timestamp("window_start", { mode: "date", withTimezone: true }).notNull(),
  windowEnd: timestamp("window_end", { mode: "date", withTimezone: true }).notNull(),
  evidenceCutoffAt: timestamp("evidence_cutoff_at", { mode: "date", withTimezone: true }).notNull(),
  signalIds: jsonb("signal_ids").$type<string[]>().notNull(),
  inputChecksum: text("input_checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  calculatedBy: uuid("calculated_by").references(() => users.id, { onDelete: "set null" }),
  calculatedAt: timestamp("calculated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("voc_analysis_runs_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("voc_analysis_runs_version_check", sql`${table.definitionVersion} > 0`),
  check("voc_analysis_runs_status_check", sql`${table.status} in ('complete','incomplete')`),
  check("voc_analysis_runs_window_check", sql`${table.windowEnd} > ${table.windowStart} and ${table.evidenceCutoffAt} >= ${table.windowEnd}`),
  check("voc_analysis_runs_checksum_check", sql`${table.inputChecksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({ columns: [table.tenantId, table.definitionId], foreignColumns: [vocDefinitions.tenantId, vocDefinitions.id], name: "voc_analysis_runs_definition_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.definitionVersionId], foreignColumns: [vocDefinitionVersions.tenantId, vocDefinitionVersions.id], name: "voc_analysis_runs_definition_version_fk" }).onDelete("restrict"),
  unique("voc_analysis_runs_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("voc_analysis_runs_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("voc_analysis_runs_window_idx").on(table.tenantId, table.windowEnd, table.calculatedAt),
]);

export const vocThemeMetrics = pgTable("voc_theme_metrics", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  runId: uuid("run_id").notNull(),
  themeCode: text("theme_code").notNull(),
  totalOccurrences: integer("total_occurrences").notNull(),
  negativeOccurrences: integer("negative_occurrences").notNull(),
  negativeBps: integer("negative_bps"),
  weightedScore: bigint("weighted_score", { mode: "number" }).notNull(),
  sourceCounts: jsonb("source_counts").$type<Record<CustomerSignalSource, number>>().notNull(),
  signalIds: jsonb("signal_ids").$type<string[]>().notNull(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("voc_theme_metrics_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("voc_theme_metrics_values_check", sql`${table.totalOccurrences} >= 0 and ${table.negativeOccurrences} >= 0 and ${table.negativeOccurrences} <= ${table.totalOccurrences} and (${table.negativeBps} is null or ${table.negativeBps} between 0 and 10000) and ${table.weightedScore} >= 0`),
  foreignKey({ columns: [table.tenantId, table.runId], foreignColumns: [vocAnalysisRuns.tenantId, vocAnalysisRuns.id], name: "voc_theme_metrics_run_fk" }).onDelete("restrict"),
  unique("voc_theme_metrics_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("voc_theme_metrics_run_theme_unique").on(table.tenantId, table.runId, table.themeCode),
]);

export const customerRecommendations = pgTable("customer_recommendations", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  runId: uuid("run_id").notNull(),
  themeCode: text("theme_code").notNull(),
  action: text("action").$type<CustomerRecommendationAction>().notNull(),
  status: text("status").default("pending").notNull(),
  evidenceSignalIds: jsonb("evidence_signal_ids").$type<string[]>().notNull(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  reviewedAt: timestamp("reviewed_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("customer_recommendations_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("customer_recommendations_action_check", sql`${table.action} in ('investigate_product','review_listing_expectations','review_campaign_terms','review_service_process')`),
  check("customer_recommendations_status_check", sql`${table.status} in ('pending','approved','rejected')`),
  check("customer_recommendations_review_check", sql`(${table.status} = 'pending' and ${table.reviewedAt} is null) or (${table.status} in ('approved','rejected') and ${table.reviewedAt} is not null)`),
  foreignKey({ columns: [table.tenantId, table.runId], foreignColumns: [vocAnalysisRuns.tenantId, vocAnalysisRuns.id], name: "customer_recommendations_run_fk" }).onDelete("restrict"),
  unique("customer_recommendations_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("customer_recommendations_run_theme_action_unique").on(table.tenantId, table.runId, table.themeCode, table.action),
  index("customer_recommendations_status_idx").on(table.tenantId, table.status, table.createdAt),
]);

export const customerRecommendationReviewEvents = pgTable("customer_recommendation_review_events", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  recommendationId: uuid("recommendation_id").notNull(),
  decision: text("decision").notNull(),
  reasonCode: text("reason_code").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("customer_recommendation_review_events_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("customer_recommendation_review_events_decision_check", sql`${table.decision} in ('approved','rejected')`),
  foreignKey({ columns: [table.tenantId, table.recommendationId], foreignColumns: [customerRecommendations.tenantId, customerRecommendations.id], name: "customer_recommendation_review_events_recommendation_fk" }).onDelete("restrict"),
  unique("customer_recommendation_review_events_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("customer_recommendation_review_events_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  uniqueIndex("customer_recommendation_review_events_recommendation_unique").on(table.tenantId, table.recommendationId),
]);
