import type {
  FinanceFactDirection,
  FinanceFactType,
  FinanceProfitBucket,
  FinanceProfitDiagnosticView,
  FinanceStatementKind,
  FinanceStatementProvider,
} from "@yummyai/contracts/finance";
import { sql } from "drizzle-orm";
import {
  bigint,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { skus } from "./catalog.js";
import { organizations, users } from "./identity.js";
import { listings } from "./listing.js";
import { marketplaceAccounts } from "./marketplace.js";
import { fulfillmentSuppliers } from "./order-routing.js";
import { orderLines, orders } from "./order.js";

export const financeStatements = pgTable("finance_statements", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  accountId: uuid("account_id"),
  provider: text("provider").$type<FinanceStatementProvider>().notNull(),
  statementKind: text("statement_kind").$type<FinanceStatementKind>().notNull(),
  externalStatementId: text("external_statement_id").notNull(),
  scopeKey: text("scope_key").notNull(),
  periodStart: timestamp("period_start", { mode: "date", withTimezone: true }).notNull(),
  periodEnd: timestamp("period_end", { mode: "date", withTimezone: true }).notNull(),
  sourceCurrency: text("source_currency").notNull(),
  observedAt: timestamp("observed_at", { mode: "date", withTimezone: true }).notNull(),
  checksum: text("checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  recordedBy: uuid("recorded_by").references(() => users.id, { onDelete: "set null" }),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("finance_statements_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("finance_statements_provider_check", sql`${table.provider} in ('amazon','etsy','advertising','carrier','supplier','tax_authority','manual')`),
  check("finance_statements_kind_check", sql`${table.statementKind} in ('marketplace_settlement','advertising_invoice','fulfillment_invoice','carrier_invoice','supplier_invoice','tax_statement','operational_cost','manual_adjustment')`),
  check("finance_statements_period_check", sql`${table.periodEnd} >= ${table.periodStart}`),
  check("finance_statements_currency_check", sql`${table.sourceCurrency} ~ '^[A-Z]{3}$'`),
  check("finance_statements_checksum_check", sql`${table.checksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({
    columns: [table.tenantId, table.accountId],
    foreignColumns: [marketplaceAccounts.tenantId, marketplaceAccounts.id],
    name: "finance_statements_account_fk",
  }).onDelete("restrict"),
  unique("finance_statements_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("finance_statements_external_unique").on(
    table.tenantId,
    table.provider,
    table.scopeKey,
    table.externalStatementId,
  ),
  uniqueIndex("finance_statements_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("finance_statements_period_idx").on(table.tenantId, table.periodStart, table.periodEnd),
]);

export const financeFacts = pgTable("finance_facts", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  statementId: uuid("statement_id").notNull(),
  accountId: uuid("account_id"),
  lineKey: text("line_key").notNull(),
  factType: text("fact_type").$type<FinanceFactType>().notNull(),
  direction: text("direction").$type<FinanceFactDirection>().notNull(),
  amountMinor: bigint("amount_minor", { mode: "number" }).notNull(),
  currency: text("currency").notNull(),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).notNull(),
  externalReference: text("external_reference"),
  orderId: uuid("order_id"),
  orderLineId: uuid("order_line_id"),
  skuId: uuid("sku_id"),
  listingId: uuid("listing_id"),
  supplierId: uuid("supplier_id"),
  correctionKind: text("correction_kind").notNull(),
  correctsFactId: uuid("corrects_fact_id"),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("finance_facts_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("finance_facts_type_check", sql`${table.factType} in ('sale_revenue','shipping_revenue','marketplace_commission','advertising_spend','fulfillment_fee','storage_fee','refund','chargeback','procurement_cost','production_cost','freight_cost','carrier_cost','tax','other_fee')`),
  check("finance_facts_direction_check", sql`${table.direction} in ('credit','debit')`),
  check("finance_facts_amount_check", sql`${table.amountMinor} >= 0`),
  check("finance_facts_currency_check", sql`${table.currency} ~ '^[A-Z]{3}$'`),
  check("finance_facts_correction_check", sql`(${table.correctionKind} = 'original' and ${table.correctsFactId} is null) or (${table.correctionKind} in ('reversal','replacement') and ${table.correctsFactId} is not null)`),
  check("finance_facts_order_line_check", sql`${table.orderLineId} is null or ${table.orderId} is not null`),
  foreignKey({
    columns: [table.tenantId, table.statementId],
    foreignColumns: [financeStatements.tenantId, financeStatements.id],
    name: "finance_facts_statement_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.accountId],
    foreignColumns: [marketplaceAccounts.tenantId, marketplaceAccounts.id],
    name: "finance_facts_account_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.orderId],
    foreignColumns: [orders.tenantId, orders.id],
    name: "finance_facts_order_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.orderLineId],
    foreignColumns: [orderLines.tenantId, orderLines.id],
    name: "finance_facts_order_line_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.skuId],
    foreignColumns: [skus.tenantId, skus.id],
    name: "finance_facts_sku_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.listingId],
    foreignColumns: [listings.tenantId, listings.id],
    name: "finance_facts_listing_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.supplierId],
    foreignColumns: [fulfillmentSuppliers.tenantId, fulfillmentSuppliers.id],
    name: "finance_facts_supplier_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.correctsFactId],
    foreignColumns: [table.tenantId, table.id],
    name: "finance_facts_correction_fk",
  }).onDelete("restrict"),
  unique("finance_facts_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("finance_facts_statement_line_unique").on(table.tenantId, table.statementId, table.lineKey),
  uniqueIndex("finance_facts_correction_unique").on(
    table.tenantId,
    table.correctionKind,
    table.correctsFactId,
  ),
  index("finance_facts_order_idx").on(table.tenantId, table.orderId, table.orderLineId, table.occurredAt),
  index("finance_facts_catalog_idx").on(table.tenantId, table.skuId, table.listingId, table.occurredAt),
  index("finance_facts_type_idx").on(table.tenantId, table.factType, table.occurredAt),
]);

export const financeFxRates = pgTable("finance_fx_rates", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  source: text("source").notNull(),
  baseCurrency: text("base_currency").notNull(),
  quoteCurrency: text("quote_currency").notNull(),
  rateNumerator: bigint("rate_numerator", { mode: "number" }).notNull(),
  rateDenominator: bigint("rate_denominator", { mode: "number" }).notNull(),
  effectiveAt: timestamp("effective_at", { mode: "date", withTimezone: true }).notNull(),
  retrievedAt: timestamp("retrieved_at", { mode: "date", withTimezone: true }).notNull(),
  checksum: text("checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  recordedBy: uuid("recorded_by").references(() => users.id, { onDelete: "set null" }),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("finance_fx_rates_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("finance_fx_rates_pair_check", sql`${table.baseCurrency} ~ '^[A-Z]{3}$' and ${table.quoteCurrency} ~ '^[A-Z]{3}$' and ${table.baseCurrency} <> ${table.quoteCurrency}`),
  check("finance_fx_rates_rate_check", sql`${table.rateNumerator} > 0 and ${table.rateDenominator} > 0`),
  check("finance_fx_rates_time_check", sql`${table.retrievedAt} >= ${table.effectiveAt}`),
  check("finance_fx_rates_checksum_check", sql`${table.checksum} ~ '^[0-9a-f]{64}$'`),
  unique("finance_fx_rates_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("finance_fx_rates_identity_unique").on(
    table.tenantId,
    table.source,
    table.baseCurrency,
    table.quoteCurrency,
    table.effectiveAt,
    table.retrievedAt,
  ),
  uniqueIndex("finance_fx_rates_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("finance_fx_rates_pair_idx").on(
    table.tenantId,
    table.baseCurrency,
    table.quoteCurrency,
    table.effectiveAt,
  ),
]);

export const financeProfitMetrics = pgTable("finance_profit_metrics", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  currentVersion: integer("current_version").default(1).notNull(),
  status: text("status").default("active").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("finance_profit_metrics_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("finance_profit_metrics_version_check", sql`${table.currentVersion} > 0`),
  check("finance_profit_metrics_status_check", sql`${table.status} in ('active','inactive')`),
  unique("finance_profit_metrics_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("finance_profit_metrics_name_unique").on(table.tenantId, table.name),
  index("finance_profit_metrics_status_idx").on(table.tenantId, table.status, table.updatedAt),
]);

export const financeProfitMetricVersions = pgTable("finance_profit_metric_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  metricId: uuid("metric_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  reportingCurrency: text("reporting_currency").notNull(),
  revenueFactTypes: jsonb("revenue_fact_types").$type<FinanceFactType[]>().notNull(),
  costFactTypes: jsonb("cost_fact_types").$type<FinanceFactType[]>().notNull(),
  requiredFactTypes: jsonb("required_fact_types").$type<FinanceFactType[]>().notNull(),
  reasonCode: text("reason_code").notNull(),
  checksum: text("checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("finance_profit_metric_versions_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("finance_profit_metric_versions_number_check", sql`${table.versionNumber} > 0`),
  check("finance_profit_metric_versions_currency_check", sql`${table.reportingCurrency} ~ '^[A-Z]{3}$'`),
  check("finance_profit_metric_versions_checksum_check", sql`${table.checksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({
    columns: [table.tenantId, table.metricId],
    foreignColumns: [financeProfitMetrics.tenantId, financeProfitMetrics.id],
    name: "finance_profit_metric_versions_metric_fk",
  }).onDelete("restrict"),
  unique("finance_profit_metric_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("finance_profit_metric_versions_number_unique").on(
    table.tenantId,
    table.metricId,
    table.versionNumber,
  ),
  uniqueIndex("finance_profit_metric_versions_idempotency_unique").on(table.tenantId, table.idempotencyKey),
]);

export const financeProfitRuns = pgTable("finance_profit_runs", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  metricId: uuid("metric_id").notNull(),
  metricVersionId: uuid("metric_version_id").notNull(),
  reportingCurrency: text("reporting_currency").notNull(),
  status: text("status").notNull(),
  revenueMinor: bigint("revenue_minor", { mode: "number" }),
  costMinor: bigint("cost_minor", { mode: "number" }),
  profitMinor: bigint("profit_minor", { mode: "number" }),
  marginBps: integer("margin_bps"),
  statementIds: jsonb("statement_ids").$type<string[]>().notNull(),
  fxRateIds: jsonb("fx_rate_ids").$type<string[]>().notNull(),
  diagnostics: jsonb("diagnostics").$type<FinanceProfitDiagnosticView>().notNull(),
  inputChecksum: text("input_checksum").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  calculatedBy: uuid("calculated_by").references(() => users.id, { onDelete: "set null" }),
  calculatedAt: timestamp("calculated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("finance_profit_runs_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("finance_profit_runs_status_check", sql`${table.status} in ('complete','incomplete')`),
  check("finance_profit_runs_currency_check", sql`${table.reportingCurrency} ~ '^[A-Z]{3}$'`),
  check("finance_profit_runs_totals_check", sql`(${table.status} = 'incomplete' and ${table.revenueMinor} is null and ${table.costMinor} is null and ${table.profitMinor} is null and ${table.marginBps} is null) or (${table.status} = 'complete' and ${table.revenueMinor} is not null and ${table.costMinor} is not null and ${table.profitMinor} is not null)`),
  check("finance_profit_runs_checksum_check", sql`${table.inputChecksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({
    columns: [table.tenantId, table.metricId],
    foreignColumns: [financeProfitMetrics.tenantId, financeProfitMetrics.id],
    name: "finance_profit_runs_metric_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.metricVersionId],
    foreignColumns: [financeProfitMetricVersions.tenantId, financeProfitMetricVersions.id],
    name: "finance_profit_runs_metric_version_fk",
  }).onDelete("restrict"),
  unique("finance_profit_runs_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("finance_profit_runs_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("finance_profit_runs_metric_idx").on(table.tenantId, table.metricId, table.calculatedAt),
]);

export const financeProfitContributions = pgTable("finance_profit_contributions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  runId: uuid("run_id").notNull(),
  factId: uuid("fact_id").notNull(),
  fxRateId: uuid("fx_rate_id"),
  bucket: text("bucket").$type<FinanceProfitBucket>().notNull(),
  sourceAmountMinor: bigint("source_amount_minor", { mode: "number" }).notNull(),
  sourceCurrency: text("source_currency").notNull(),
  reportingAmountMinor: bigint("reporting_amount_minor", { mode: "number" }),
  reportingCurrency: text("reporting_currency").notNull(),
  effectSign: integer("effect_sign").notNull(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("finance_profit_contributions_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("finance_profit_contributions_bucket_check", sql`${table.bucket} in ('revenue','cost','unclassified')`),
  check("finance_profit_contributions_amount_check", sql`${table.sourceAmountMinor} >= 0 and (${table.reportingAmountMinor} is null or ${table.reportingAmountMinor} >= 0)`),
  check("finance_profit_contributions_currency_check", sql`${table.sourceCurrency} ~ '^[A-Z]{3}$' and ${table.reportingCurrency} ~ '^[A-Z]{3}$'`),
  check("finance_profit_contributions_sign_check", sql`${table.effectSign} in (-1, 1)`),
  foreignKey({
    columns: [table.tenantId, table.runId],
    foreignColumns: [financeProfitRuns.tenantId, financeProfitRuns.id],
    name: "finance_profit_contributions_run_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.factId],
    foreignColumns: [financeFacts.tenantId, financeFacts.id],
    name: "finance_profit_contributions_fact_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.fxRateId],
    foreignColumns: [financeFxRates.tenantId, financeFxRates.id],
    name: "finance_profit_contributions_fx_fk",
  }).onDelete("restrict"),
  unique("finance_profit_contributions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("finance_profit_contributions_fact_unique").on(table.tenantId, table.runId, table.factId),
  index("finance_profit_contributions_run_idx").on(table.tenantId, table.runId, table.bucket),
]);
