import type { IntegrationApiScope, WebhookDeliveryStatus, WebhookEventType } from "@yummyai/contracts/integration";
import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, unique, uniqueIndex, uuid } from "drizzle-orm/pg-core";

import { organizations, users } from "./identity.js";

export const integrationApiClients = pgTable("integration_api_clients", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), label: text("label").notNull(), keyPrefix: text("key_prefix").notNull(), secretDigest: text("secret_digest").notNull(), scopes: jsonb("scopes").$type<IntegrationApiScope[]>().notNull(), status: text("status").default("active").notNull(), expiresAt: timestamp("expires_at", { mode: "date", withTimezone: true }), idempotencyKey: text("idempotency_key").notNull(), createdBy: uuid("created_by").notNull().references(() => users.id, { onDelete: "restrict" }), createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(), revokedAt: timestamp("revoked_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("integration_api_clients_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("integration_api_clients_status_check", sql`${table.status} in ('active','revoked')`), check("integration_api_clients_digest_check", sql`${table.secretDigest} ~ '^[0-9a-f]{64}$'`), unique("integration_api_clients_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("integration_api_clients_prefix_unique").on(table.keyPrefix), uniqueIndex("integration_api_clients_idempotency_unique").on(table.tenantId, table.idempotencyKey), index("integration_api_clients_status_idx").on(table.tenantId, table.status, table.expiresAt),
]);

export const integrationApiClientEvents = pgTable("integration_api_client_events", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), clientId: uuid("client_id").notNull(), action: text("action").notNull(), reasonCode: text("reason_code").notNull(), idempotencyKey: text("idempotency_key").notNull(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("integration_api_client_events_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("integration_api_client_events_action_check", sql`${table.action} in ('created','revoked')`), foreignKey({ columns: [table.tenantId, table.clientId], foreignColumns: [integrationApiClients.tenantId, integrationApiClients.id], name: "integration_api_client_events_client_fk" }).onDelete("restrict"), unique("integration_api_client_events_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("integration_api_client_events_idempotency_unique").on(table.tenantId, table.clientId, table.idempotencyKey),
]);

export const webhookEndpoints = pgTable("webhook_endpoints", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), label: text("label").notNull(), url: text("url").notNull(), eventTypes: jsonb("event_types").$type<WebhookEventType[]>().notNull(), maxAttempts: integer("max_attempts").notNull(), status: text("status").default("active").notNull(), version: integer("version").default(1).notNull(), encryptedSigningSecret: text("encrypted_signing_secret").notNull(), signingKeyPrefix: text("signing_key_prefix").notNull(), idempotencyKey: text("idempotency_key").notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("webhook_endpoints_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("webhook_endpoints_attempts_check", sql`${table.maxAttempts} between 1 and 10`), check("webhook_endpoints_status_check", sql`${table.status} in ('active','disabled')`), check("webhook_endpoints_version_check", sql`${table.version} > 0`), unique("webhook_endpoints_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("webhook_endpoints_idempotency_unique").on(table.tenantId, table.idempotencyKey), index("webhook_endpoints_status_idx").on(table.tenantId, table.status, table.updatedAt),
]);

export const webhookEndpointEvents = pgTable("webhook_endpoint_events", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), endpointId: uuid("endpoint_id").notNull(), version: integer("version").notNull(), action: text("action").notNull(), reasonCode: text("reason_code").notNull(), configurationChecksum: text("configuration_checksum").notNull(), idempotencyKey: text("idempotency_key").notNull(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("webhook_endpoint_events_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("webhook_endpoint_events_version_check", sql`${table.version} > 0`), check("webhook_endpoint_events_action_check", sql`${table.action} in ('created','updated','secret_rotated')`), check("webhook_endpoint_events_checksum_check", sql`${table.configurationChecksum} ~ '^[0-9a-f]{64}$'`), foreignKey({ columns: [table.tenantId, table.endpointId], foreignColumns: [webhookEndpoints.tenantId, webhookEndpoints.id], name: "webhook_endpoint_events_endpoint_fk" }).onDelete("restrict"), unique("webhook_endpoint_events_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("webhook_endpoint_events_version_unique").on(table.tenantId, table.endpointId, table.version), uniqueIndex("webhook_endpoint_events_idempotency_unique").on(table.tenantId, table.endpointId, table.idempotencyKey),
]);

export const webhookEvents = pgTable("webhook_events", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), eventType: text("event_type").$type<WebhookEventType>().notNull(), resourceType: text("resource_type").notNull(), resourceId: uuid("resource_id").notNull(), payload: jsonb("payload").$type<Record<string, unknown> | null>(), payloadChecksum: text("payload_checksum").notNull(), occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).notNull(), idempotencyKey: text("idempotency_key").notNull(), recordedBy: uuid("recorded_by").references(() => users.id, { onDelete: "set null" }), recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(), payloadRedactedAt: timestamp("payload_redacted_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("webhook_events_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("webhook_events_type_check", sql`${table.eventType} in ('forecast.completed','forecast.overridden','operating.reconciliation.opened','operating.reconciliation.resolved','webhook.test')`), check("webhook_events_checksum_check", sql`${table.payloadChecksum} ~ '^[0-9a-f]{64}$'`), unique("webhook_events_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("webhook_events_idempotency_unique").on(table.tenantId, table.idempotencyKey), index("webhook_events_recorded_idx").on(table.tenantId, table.eventType, table.recordedAt),
]);

export const webhookDeliveries = pgTable("webhook_deliveries", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), eventId: uuid("event_id").notNull(), endpointId: uuid("endpoint_id").notNull(), status: text("status").$type<WebhookDeliveryStatus>().default("pending").notNull(), attemptCount: integer("attempt_count").default(0).notNull(), maxAttempts: integer("max_attempts").notNull(), nextAttemptAt: timestamp("next_attempt_at", { mode: "date", withTimezone: true }), replayOfDeliveryId: uuid("replay_of_delivery_id"), idempotencyKey: text("idempotency_key").notNull(), requestedBy: uuid("requested_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(), completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("webhook_deliveries_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("webhook_deliveries_status_check", sql`${table.status} in ('pending','delivering','retry_scheduled','succeeded','dead_letter')`), check("webhook_deliveries_attempts_check", sql`${table.attemptCount} >= 0 and ${table.maxAttempts} between 1 and 10 and ${table.attemptCount} <= ${table.maxAttempts}`), foreignKey({ columns: [table.tenantId, table.eventId], foreignColumns: [webhookEvents.tenantId, webhookEvents.id], name: "webhook_deliveries_event_fk" }).onDelete("restrict"), foreignKey({ columns: [table.tenantId, table.endpointId], foreignColumns: [webhookEndpoints.tenantId, webhookEndpoints.id], name: "webhook_deliveries_endpoint_fk" }).onDelete("restrict"), unique("webhook_deliveries_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("webhook_deliveries_idempotency_unique").on(table.tenantId, table.idempotencyKey), index("webhook_deliveries_status_idx").on(table.tenantId, table.status, table.nextAttemptAt),
]);

export const webhookDeliveryAttempts = pgTable("webhook_delivery_attempts", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), deliveryId: uuid("delivery_id").notNull(), attemptNumber: integer("attempt_number").notNull(), requestTimestamp: timestamp("request_timestamp", { mode: "date", withTimezone: true }).notNull(), signatureVersion: text("signature_version").notNull(), responseStatus: integer("response_status"), outcome: text("outcome").notNull(), failureCode: text("failure_code"), completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("webhook_delivery_attempts_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("webhook_delivery_attempts_number_check", sql`${table.attemptNumber} > 0`), check("webhook_delivery_attempts_signature_check", sql`${table.signatureVersion} = 'v1'`), check("webhook_delivery_attempts_status_check", sql`${table.responseStatus} is null or ${table.responseStatus} between 100 and 599`), check("webhook_delivery_attempts_outcome_check", sql`${table.outcome} in ('succeeded','retryable_failure','terminal_failure')`), foreignKey({ columns: [table.tenantId, table.deliveryId], foreignColumns: [webhookDeliveries.tenantId, webhookDeliveries.id], name: "webhook_delivery_attempts_delivery_fk" }).onDelete("restrict"), unique("webhook_delivery_attempts_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("webhook_delivery_attempts_number_unique").on(table.tenantId, table.deliveryId, table.attemptNumber),
]);

export const integrationRetentionRuns = pgTable("integration_retention_runs", {
  id: uuid("id").primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), payloadsBefore: timestamp("payloads_before", { mode: "date", withTimezone: true }).notNull(), redactedEventCount: integer("redacted_event_count").notNull(), checksum: text("checksum").notNull(), idempotencyKey: text("idempotency_key").notNull(), completedBy: uuid("completed_by").references(() => users.id, { onDelete: "set null" }), completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("integration_retention_runs_id_check", sql`substring(${table.id}::text from 15 for 1) = '7'`), check("integration_retention_runs_count_check", sql`${table.redactedEventCount} >= 0`), check("integration_retention_runs_checksum_check", sql`${table.checksum} ~ '^[0-9a-f]{64}$'`), unique("integration_retention_runs_tenant_id_unique").on(table.tenantId, table.id), uniqueIndex("integration_retention_runs_idempotency_unique").on(table.tenantId, table.idempotencyKey),
]);
