import { sql } from "drizzle-orm";
import {
  bigint,
  check,
  foreignKey,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { skus } from "./catalog.js";
import { organizations, users } from "./identity.js";

export const inventoryWarehouses = pgTable("inventory_warehouses", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  code: text("code").notNull(),
  name: text("name").notNull(),
  type: text("type").notNull(),
  countryCode: text("country_code"),
  timeZone: text("time_zone").notNull(),
  status: text("status").default("active").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_warehouses_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_warehouses_type_check", sql`${table.type} in ('owned','third_party','fba','supplier','virtual')`),
  check("inventory_warehouses_country_check", sql`${table.countryCode} is null or ${table.countryCode} ~ '^[A-Z]{2}$'`),
  check("inventory_warehouses_status_check", sql`${table.status} in ('active','inactive')`),
  uniqueIndex("inventory_warehouses_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_warehouses_code_unique").on(table.tenantId, table.code),
  index("inventory_warehouses_status_idx").on(table.tenantId, table.status, table.name),
]);

export const inventoryLocations = pgTable("inventory_locations", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  warehouseId: uuid("warehouse_id").notNull(),
  code: text("code").notNull(),
  name: text("name").notNull(),
  status: text("status").default("active").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_locations_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_locations_status_check", sql`${table.status} in ('active','inactive')`),
  foreignKey({
    columns: [table.tenantId, table.warehouseId],
    foreignColumns: [inventoryWarehouses.tenantId, inventoryWarehouses.id],
    name: "inventory_locations_warehouse_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_locations_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_locations_code_unique").on(table.tenantId, table.warehouseId, table.code),
  index("inventory_locations_warehouse_idx").on(table.tenantId, table.warehouseId, table.status),
]);

export const inventoryStockItems = pgTable("inventory_stock_items", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  skuId: uuid("sku_id"),
  code: text("code").notNull(),
  name: text("name").notNull(),
  baseUnit: text("base_unit").notNull(),
  status: text("status").default("active").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_stock_items_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_stock_items_unit_check", sql`${table.baseUnit} in ('each','pair','set','meter','gram','kilogram')`),
  check("inventory_stock_items_status_check", sql`${table.status} in ('active','inactive')`),
  foreignKey({
    columns: [table.tenantId, table.skuId],
    foreignColumns: [skus.tenantId, skus.id],
    name: "inventory_stock_items_sku_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_stock_items_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_stock_items_code_unique").on(table.tenantId, table.code),
  uniqueIndex("inventory_stock_items_sku_unique").on(table.tenantId, table.skuId).where(sql`${table.skuId} is not null`),
  index("inventory_stock_items_status_idx").on(table.tenantId, table.status, table.name),
]);

export const inventoryLots = pgTable("inventory_lots", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  stockItemId: uuid("stock_item_id").notNull(),
  code: text("code").notNull(),
  sourceType: text("source_type").notNull(),
  sourceId: text("source_id").notNull(),
  unitCostMinor: bigint("unit_cost_minor", { mode: "number" }),
  unitCostCurrency: text("unit_cost_currency"),
  receivedAt: timestamp("received_at", { mode: "date", withTimezone: true }),
  expiresAt: timestamp("expires_at", { mode: "date", withTimezone: true }),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_lots_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_lots_source_check", sql`${table.sourceType} in ('opening','order','order_line','receipt','return','transfer','adjustment','reconciliation','manual')`),
  check("inventory_lots_cost_check", sql`(${table.unitCostMinor} is null and ${table.unitCostCurrency} is null) or (${table.unitCostMinor} >= 0 and ${table.unitCostCurrency} ~ '^[A-Z]{3}$')`),
  check("inventory_lots_expiry_check", sql`${table.expiresAt} is null or ${table.receivedAt} is null or ${table.expiresAt} > ${table.receivedAt}`),
  foreignKey({
    columns: [table.tenantId, table.stockItemId],
    foreignColumns: [inventoryStockItems.tenantId, inventoryStockItems.id],
    name: "inventory_lots_stock_item_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_lots_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_lots_stock_item_id_unique").on(table.tenantId, table.stockItemId, table.id),
  uniqueIndex("inventory_lots_code_unique").on(table.tenantId, table.stockItemId, table.code),
  index("inventory_lots_expiry_idx").on(table.tenantId, table.stockItemId, table.expiresAt),
]);

export const inventoryMovements = pgTable("inventory_movements", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  stockItemId: uuid("stock_item_id").notNull(),
  locationId: uuid("location_id").notNull(),
  lotId: uuid("lot_id"),
  bucket: text("bucket").notNull(),
  type: text("type").notNull(),
  quantityDelta: integer("quantity_delta").notNull(),
  unit: text("unit").notNull(),
  sourceType: text("source_type").notNull(),
  sourceId: text("source_id").notNull(),
  reasonCode: text("reason_code").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  recordedBy: uuid("recorded_by").references(() => users.id, { onDelete: "set null" }),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).notNull(),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_movements_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_movements_bucket_check", sql`${table.bucket} in ('physical','in_transit','provider','virtual')`),
  check("inventory_movements_type_check", sql`${table.type} in ('opening','receipt','allocation','release','pick','ship','return','adjustment','transfer_outbound','transfer_inbound','damage','reconciliation')`),
  check("inventory_movements_quantity_check", sql`${table.quantityDelta} <> 0`),
  check("inventory_movements_unit_check", sql`${table.unit} in ('each','pair','set','meter','gram','kilogram')`),
  check("inventory_movements_source_check", sql`${table.sourceType} in ('opening','order','order_line','receipt','return','transfer','adjustment','reconciliation','manual')`),
  foreignKey({
    columns: [table.tenantId, table.stockItemId],
    foreignColumns: [inventoryStockItems.tenantId, inventoryStockItems.id],
    name: "inventory_movements_stock_item_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.locationId],
    foreignColumns: [inventoryLocations.tenantId, inventoryLocations.id],
    name: "inventory_movements_location_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.stockItemId, table.lotId],
    foreignColumns: [inventoryLots.tenantId, inventoryLots.stockItemId, inventoryLots.id],
    name: "inventory_movements_lot_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_movements_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_movements_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("inventory_movements_dimension_idx").on(table.tenantId, table.stockItemId, table.locationId, table.lotId, table.occurredAt),
  index("inventory_movements_source_idx").on(table.tenantId, table.sourceType, table.sourceId),
]);

export const inventoryBalances = pgTable("inventory_balances", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  dimensionKey: text("dimension_key").notNull(),
  stockItemId: uuid("stock_item_id").notNull(),
  locationId: uuid("location_id").notNull(),
  lotId: uuid("lot_id"),
  unit: text("unit").notNull(),
  physicalQuantity: integer("physical_quantity").default(0).notNull(),
  reservedQuantity: integer("reserved_quantity").default(0).notNull(),
  inTransitQuantity: integer("in_transit_quantity").default(0).notNull(),
  providerQuantity: integer("provider_quantity").default(0).notNull(),
  virtualQuantity: integer("virtual_quantity").default(0).notNull(),
  projectionVersion: integer("projection_version").default(1).notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_balances_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_balances_unit_check", sql`${table.unit} in ('each','pair','set','meter','gram','kilogram')`),
  check("inventory_balances_quantities_check", sql`${table.physicalQuantity} >= 0 and ${table.reservedQuantity} >= 0 and ${table.physicalQuantity} >= ${table.reservedQuantity} and ${table.inTransitQuantity} >= 0 and ${table.providerQuantity} >= 0 and ${table.virtualQuantity} >= 0`),
  check("inventory_balances_version_check", sql`${table.projectionVersion} > 0`),
  foreignKey({
    columns: [table.tenantId, table.stockItemId],
    foreignColumns: [inventoryStockItems.tenantId, inventoryStockItems.id],
    name: "inventory_balances_stock_item_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.locationId],
    foreignColumns: [inventoryLocations.tenantId, inventoryLocations.id],
    name: "inventory_balances_location_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.stockItemId, table.lotId],
    foreignColumns: [inventoryLots.tenantId, inventoryLots.stockItemId, inventoryLots.id],
    name: "inventory_balances_lot_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_balances_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_balances_dimension_unique").on(table.tenantId, table.dimensionKey),
  index("inventory_balances_stock_idx").on(table.tenantId, table.stockItemId, table.locationId),
]);

export const inventoryReservations = pgTable("inventory_reservations", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  stockItemId: uuid("stock_item_id").notNull(),
  locationId: uuid("location_id").notNull(),
  lotId: uuid("lot_id"),
  quantity: integer("quantity").notNull(),
  unit: text("unit").notNull(),
  sourceType: text("source_type").notNull(),
  sourceId: text("source_id").notNull(),
  status: text("status").default("active").notNull(),
  version: integer("version").default(1).notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  expiresAt: timestamp("expires_at", { mode: "date", withTimezone: true }),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_reservations_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_reservations_quantity_check", sql`${table.quantity} > 0`),
  check("inventory_reservations_unit_check", sql`${table.unit} in ('each','pair','set','meter','gram','kilogram')`),
  check("inventory_reservations_source_check", sql`${table.sourceType} in ('order','order_line','transfer','manual')`),
  check("inventory_reservations_status_check", sql`${table.status} in ('active','released','fulfilled','cancelled')`),
  check("inventory_reservations_version_check", sql`${table.version} > 0`),
  foreignKey({
    columns: [table.tenantId, table.stockItemId],
    foreignColumns: [inventoryStockItems.tenantId, inventoryStockItems.id],
    name: "inventory_reservations_stock_item_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.locationId],
    foreignColumns: [inventoryLocations.tenantId, inventoryLocations.id],
    name: "inventory_reservations_location_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.stockItemId, table.lotId],
    foreignColumns: [inventoryLots.tenantId, inventoryLots.stockItemId, inventoryLots.id],
    name: "inventory_reservations_lot_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_reservations_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_reservations_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("inventory_reservations_dimension_idx").on(table.tenantId, table.stockItemId, table.locationId, table.lotId, table.status),
  index("inventory_reservations_expiry_idx").on(table.tenantId, table.status, table.expiresAt),
]);

export const inventoryReservationEvents = pgTable("inventory_reservation_events", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  reservationId: uuid("reservation_id").notNull(),
  sequence: integer("sequence").notNull(),
  action: text("action").notNull(),
  fromStatus: text("from_status"),
  toStatus: text("to_status").notNull(),
  reasonCode: text("reason_code").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_reservation_events_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_reservation_events_sequence_check", sql`${table.sequence} > 0`),
  check("inventory_reservation_events_action_check", sql`${table.action} in ('reserved','released','fulfilled','cancelled')`),
  check("inventory_reservation_events_status_check", sql`${table.toStatus} in ('active','released','fulfilled','cancelled')`),
  foreignKey({
    columns: [table.tenantId, table.reservationId],
    foreignColumns: [inventoryReservations.tenantId, inventoryReservations.id],
    name: "inventory_reservation_events_reservation_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_reservation_events_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_reservation_events_sequence_unique").on(table.tenantId, table.reservationId, table.sequence),
  uniqueIndex("inventory_reservation_events_idempotency_unique").on(table.tenantId, table.reservationId, table.idempotencyKey),
]);

export const inventoryTransfers = pgTable("inventory_transfers", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  stockItemId: uuid("stock_item_id").notNull(),
  lotId: uuid("lot_id"),
  sourceLocationId: uuid("source_location_id").notNull(),
  destinationLocationId: uuid("destination_location_id").notNull(),
  quantity: integer("quantity").notNull(),
  unit: text("unit").notNull(),
  status: text("status").default("draft").notNull(),
  version: integer("version").default(1).notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_transfers_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_transfers_locations_check", sql`${table.sourceLocationId} <> ${table.destinationLocationId}`),
  check("inventory_transfers_quantity_check", sql`${table.quantity} > 0`),
  check("inventory_transfers_unit_check", sql`${table.unit} in ('each','pair','set','meter','gram','kilogram')`),
  check("inventory_transfers_status_check", sql`${table.status} in ('draft','in_transit','received','cancelled')`),
  check("inventory_transfers_version_check", sql`${table.version} > 0`),
  foreignKey({
    columns: [table.tenantId, table.stockItemId],
    foreignColumns: [inventoryStockItems.tenantId, inventoryStockItems.id],
    name: "inventory_transfers_stock_item_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.stockItemId, table.lotId],
    foreignColumns: [inventoryLots.tenantId, inventoryLots.stockItemId, inventoryLots.id],
    name: "inventory_transfers_lot_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.sourceLocationId],
    foreignColumns: [inventoryLocations.tenantId, inventoryLocations.id],
    name: "inventory_transfers_source_location_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.destinationLocationId],
    foreignColumns: [inventoryLocations.tenantId, inventoryLocations.id],
    name: "inventory_transfers_destination_location_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_transfers_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_transfers_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("inventory_transfers_status_idx").on(table.tenantId, table.status, table.updatedAt),
]);

export const inventoryTransferEvents = pgTable("inventory_transfer_events", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  transferId: uuid("transfer_id").notNull(),
  sequence: integer("sequence").notNull(),
  action: text("action").notNull(),
  fromStatus: text("from_status"),
  toStatus: text("to_status").notNull(),
  reasonCode: text("reason_code").notNull(),
  debitMovementId: uuid("debit_movement_id"),
  creditMovementId: uuid("credit_movement_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_transfer_events_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_transfer_events_sequence_check", sql`${table.sequence} > 0`),
  check("inventory_transfer_events_action_check", sql`${table.action} in ('created','dispatched','received','cancelled')`),
  check("inventory_transfer_events_status_check", sql`${table.toStatus} in ('draft','in_transit','received','cancelled')`),
  check("inventory_transfer_events_movements_check", sql`((${table.action} in ('dispatched','received')) and ${table.debitMovementId} is not null and ${table.creditMovementId} is not null) or ((${table.action} in ('created','cancelled')) and ${table.debitMovementId} is null and ${table.creditMovementId} is null)`),
  foreignKey({
    columns: [table.tenantId, table.transferId],
    foreignColumns: [inventoryTransfers.tenantId, inventoryTransfers.id],
    name: "inventory_transfer_events_transfer_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.debitMovementId],
    foreignColumns: [inventoryMovements.tenantId, inventoryMovements.id],
    name: "inventory_transfer_events_debit_movement_fk",
  }).onDelete("restrict"),
  foreignKey({
    columns: [table.tenantId, table.creditMovementId],
    foreignColumns: [inventoryMovements.tenantId, inventoryMovements.id],
    name: "inventory_transfer_events_credit_movement_fk",
  }).onDelete("restrict"),
  uniqueIndex("inventory_transfer_events_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_transfer_events_sequence_unique").on(table.tenantId, table.transferId, table.sequence),
  uniqueIndex("inventory_transfer_events_idempotency_unique").on(table.tenantId, table.transferId, table.idempotencyKey),
]);

export const inventoryProjectionRebuilds = pgTable("inventory_projection_rebuilds", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  idempotencyKey: text("idempotency_key").notNull(),
  balanceCount: integer("balance_count").notNull(),
  aggregateChecksum: text("aggregate_checksum").notNull(),
  initiatedBy: uuid("initiated_by").references(() => users.id, { onDelete: "set null" }),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("inventory_projection_rebuilds_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("inventory_projection_rebuilds_count_check", sql`${table.balanceCount} >= 0`),
  check("inventory_projection_rebuilds_checksum_check", sql`${table.aggregateChecksum} ~ '^[0-9a-f]{64}$'`),
  uniqueIndex("inventory_projection_rebuilds_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("inventory_projection_rebuilds_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("inventory_projection_rebuilds_time_idx").on(table.tenantId, table.occurredAt),
]);
