import { sql } from "drizzle-orm";
import { bigint, check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

import { skus } from "./catalog.js";
import { designVersions } from "./design.js";
import { organizations, users } from "./identity.js";
import { orderLines, orders } from "./order.js";
import { fulfillmentSuppliers, orderRoutingDecisions, purchaseOrderVersions } from "./order-routing.js";

export const productionOrders = pgTable("production_orders", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  orderId: uuid("order_id").notNull(),
  orderLineId: uuid("order_line_id").notNull(),
  supplierId: uuid("supplier_id").notNull(),
  routingDecisionId: uuid("routing_decision_id").notNull(),
  purchaseOrderVersionId: uuid("purchase_order_version_id").notNull(),
  parentProductionOrderId: uuid("parent_production_order_id"),
  source: text("source").default("initial").notNull(),
  status: text("status").default("planned").notNull(),
  projectionVersion: integer("projection_version").default(1).notNull(),
  currentVersionNumber: integer("current_version_number").default(1).notNull(),
  expectedCompletionAt: timestamp("expected_completion_at", { mode: "date", withTimezone: true }).notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_orders_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_orders_source_check", sql`${table.source} in ('initial','remake')`),
  check("production_orders_status_check", sql`${table.status} in ('planned','submitted','acknowledged','in_production','quality_hold','completed','cancel_requested','cancelled','failed')`),
  check("production_orders_versions_check", sql`${table.projectionVersion} > 0 and ${table.currentVersionNumber} > 0`),
  check("production_orders_parent_check", sql`(${table.source} = 'initial' and ${table.parentProductionOrderId} is null) or (${table.source} = 'remake' and ${table.parentProductionOrderId} is not null)`),
  foreignKey({ columns: [table.tenantId, table.orderId], foreignColumns: [orders.tenantId, orders.id], name: "production_orders_order_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.orderLineId], foreignColumns: [orderLines.tenantId, orderLines.id], name: "production_orders_line_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.supplierId], foreignColumns: [fulfillmentSuppliers.tenantId, fulfillmentSuppliers.id], name: "production_orders_supplier_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.routingDecisionId], foreignColumns: [orderRoutingDecisions.tenantId, orderRoutingDecisions.id], name: "production_orders_routing_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.purchaseOrderVersionId], foreignColumns: [purchaseOrderVersions.tenantId, purchaseOrderVersions.id], name: "production_orders_purchase_version_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.parentProductionOrderId], foreignColumns: [table.tenantId, table.id], name: "production_orders_parent_fk" }).onDelete("restrict"),
  uniqueIndex("production_orders_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_orders_idempotency_unique").on(table.tenantId, table.orderLineId, table.idempotencyKey),
  index("production_orders_queue_idx").on(table.tenantId, table.status, table.expectedCompletionAt),
  index("production_orders_lineage_idx").on(table.tenantId, table.parentProductionOrderId, table.createdAt),
]);

export const productionOrderVersions = pgTable("production_order_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  productionOrderId: uuid("production_order_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  quantity: integer("quantity").notNull(),
  designVersionId: uuid("design_version_id"),
  productionAssetIds: jsonb("production_asset_ids").$type<string[]>().default(sql`'[]'::jsonb`).notNull(),
  encryptedInstructions: text("encrypted_instructions").notNull(),
  instructionsChecksum: text("instructions_checksum").notNull(),
  expectedCompletionAt: timestamp("expected_completion_at", { mode: "date", withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_order_versions_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_order_versions_version_check", sql`${table.versionNumber} > 0 and ${table.quantity} > 0`),
  check("production_order_versions_checksum_check", sql`${table.instructionsChecksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({ columns: [table.tenantId, table.productionOrderId], foreignColumns: [productionOrders.tenantId, productionOrders.id], name: "production_order_versions_order_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.designVersionId], foreignColumns: [designVersions.tenantId, designVersions.id], name: "production_order_versions_design_fk" }).onDelete("restrict"),
  uniqueIndex("production_order_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_order_versions_number_unique").on(table.tenantId, table.productionOrderId, table.versionNumber),
]);

export const productionMilestoneEvents = pgTable("production_milestone_events", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  productionOrderId: uuid("production_order_id").notNull(),
  sequence: integer("sequence").notNull(),
  type: text("type").notNull(),
  externalEventId: text("external_event_id"),
  evidenceCode: text("evidence_code").notNull(),
  encryptedEvidenceNote: text("encrypted_evidence_note"),
  evidenceAssetIds: jsonb("evidence_asset_ids").$type<string[]>().default(sql`'[]'::jsonb`).notNull(),
  actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).notNull(),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_milestone_events_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_milestone_events_sequence_check", sql`${table.sequence} > 0`),
  check("production_milestone_events_type_check", sql`${table.type} in ('submitted','acknowledged','started','completed','failed','cancel_requested','cancelled')`),
  foreignKey({ columns: [table.tenantId, table.productionOrderId], foreignColumns: [productionOrders.tenantId, productionOrders.id], name: "production_milestone_events_order_fk" }).onDelete("restrict"),
  uniqueIndex("production_milestone_events_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_milestone_events_sequence_unique").on(table.tenantId, table.productionOrderId, table.sequence),
  uniqueIndex("production_milestone_events_external_unique").on(table.tenantId, table.productionOrderId, table.externalEventId),
]);

export const qualityStandardVersions = pgTable("quality_standard_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  versionNumber: integer("version_number").notNull(),
  skuId: uuid("sku_id"),
  supplierId: uuid("supplier_id"),
  minimumScoreBps: integer("minimum_score_bps").notNull(),
  criteria: jsonb("criteria").$type<Array<{ code: string; label: string; weightBps: number; blocking: boolean }>>().notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("quality_standard_versions_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("quality_standard_versions_version_check", sql`${table.versionNumber} > 0`),
  check("quality_standard_versions_score_check", sql`${table.minimumScoreBps} between 0 and 10000`),
  foreignKey({ columns: [table.tenantId, table.skuId], foreignColumns: [skus.tenantId, skus.id], name: "quality_standard_versions_sku_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.supplierId], foreignColumns: [fulfillmentSuppliers.tenantId, fulfillmentSuppliers.id], name: "quality_standard_versions_supplier_fk" }).onDelete("restrict"),
  uniqueIndex("quality_standard_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("quality_standard_versions_name_version_unique").on(table.tenantId, table.name, table.versionNumber),
  index("quality_standard_versions_scope_idx").on(table.tenantId, table.skuId, table.supplierId, table.createdAt),
]);

export const qualityInspections = pgTable("quality_inspections", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  productionOrderId: uuid("production_order_id").notNull(),
  qualityStandardVersionId: uuid("quality_standard_version_id").notNull(),
  result: text("result").notNull(),
  scoreBps: integer("score_bps").notNull(),
  evidenceAssetIds: jsonb("evidence_asset_ids").$type<string[]>().default(sql`'[]'::jsonb`).notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  inspectedBy: uuid("inspected_by").references(() => users.id, { onDelete: "set null" }),
  inspectedAt: timestamp("inspected_at", { mode: "date", withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("quality_inspections_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("quality_inspections_result_check", sql`${table.result} in ('passed','failed')`),
  check("quality_inspections_score_check", sql`${table.scoreBps} between 0 and 10000`),
  foreignKey({ columns: [table.tenantId, table.productionOrderId], foreignColumns: [productionOrders.tenantId, productionOrders.id], name: "quality_inspections_order_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.qualityStandardVersionId], foreignColumns: [qualityStandardVersions.tenantId, qualityStandardVersions.id], name: "quality_inspections_standard_fk" }).onDelete("restrict"),
  uniqueIndex("quality_inspections_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("quality_inspections_idempotency_unique").on(table.tenantId, table.productionOrderId, table.idempotencyKey),
  index("quality_inspections_result_idx").on(table.tenantId, table.result, table.inspectedAt),
]);

export const qualityDefects = pgTable("quality_defects", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  productionOrderId: uuid("production_order_id").notNull(),
  inspectionId: uuid("inspection_id").notNull(),
  code: text("code").notNull(),
  severity: text("severity").notNull(),
  responsibility: text("responsibility").notNull(),
  disposition: text("disposition").notNull(),
  encryptedDetail: text("encrypted_detail").notNull(),
  detailChecksum: text("detail_checksum").notNull(),
  evidenceAssetIds: jsonb("evidence_asset_ids").$type<string[]>().default(sql`'[]'::jsonb`).notNull(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("quality_defects_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("quality_defects_severity_check", sql`${table.severity} in ('minor','major','critical')`),
  check("quality_defects_responsibility_check", sql`${table.responsibility} in ('supplier','internal','carrier','customer','unknown')`),
  check("quality_defects_disposition_check", sql`${table.disposition} in ('accept','rework','remake','reship','refund','cancel')`),
  check("quality_defects_checksum_check", sql`${table.detailChecksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({ columns: [table.tenantId, table.productionOrderId], foreignColumns: [productionOrders.tenantId, productionOrders.id], name: "quality_defects_order_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.inspectionId], foreignColumns: [qualityInspections.tenantId, qualityInspections.id], name: "quality_defects_inspection_fk" }).onDelete("restrict"),
  uniqueIndex("quality_defects_tenant_id_unique").on(table.tenantId, table.id),
  index("quality_defects_responsibility_idx").on(table.tenantId, table.responsibility, table.severity, table.createdAt),
]);

export const productionRecoveryCases = pgTable("production_recovery_cases", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  orderId: uuid("order_id").notNull(),
  originalProductionOrderId: uuid("original_production_order_id").notNull(),
  defectId: uuid("defect_id"),
  type: text("type").notNull(),
  status: text("status").default("open").notNull(),
  projectionVersion: integer("projection_version").default(1).notNull(),
  encryptedReason: text("encrypted_reason").notNull(),
  reasonChecksum: text("reason_checksum").notNull(),
  compensationAmountMinor: bigint("compensation_amount_minor", { mode: "number" }),
  compensationCurrency: text("compensation_currency"),
  expectedCompletionAt: timestamp("expected_completion_at", { mode: "date", withTimezone: true }),
  idempotencyKey: text("idempotency_key").notNull(),
  openedBy: uuid("opened_by").references(() => users.id, { onDelete: "set null" }),
  openedAt: timestamp("opened_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_recovery_cases_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_recovery_cases_type_check", sql`${table.type} in ('remake','reship','cancellation_compensation')`),
  check("production_recovery_cases_status_check", sql`${table.status} in ('open','in_progress','resolved','cancelled')`),
  check("production_recovery_cases_version_check", sql`${table.projectionVersion} > 0`),
  check("production_recovery_cases_checksum_check", sql`${table.reasonChecksum} ~ '^[0-9a-f]{64}$'`),
  check("production_recovery_cases_compensation_check", sql`(${table.type} = 'cancellation_compensation' and ${table.compensationAmountMinor} is not null and ${table.compensationCurrency} ~ '^[A-Z]{3}$') or (${table.type} <> 'cancellation_compensation' and ${table.compensationAmountMinor} is null and ${table.compensationCurrency} is null)`),
  foreignKey({ columns: [table.tenantId, table.orderId], foreignColumns: [orders.tenantId, orders.id], name: "production_recovery_cases_order_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.originalProductionOrderId], foreignColumns: [productionOrders.tenantId, productionOrders.id], name: "production_recovery_cases_production_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.defectId], foreignColumns: [qualityDefects.tenantId, qualityDefects.id], name: "production_recovery_cases_defect_fk" }).onDelete("restrict"),
  uniqueIndex("production_recovery_cases_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_recovery_cases_idempotency_unique").on(table.tenantId, table.originalProductionOrderId, table.idempotencyKey),
  index("production_recovery_cases_queue_idx").on(table.tenantId, table.status, table.type, table.updatedAt),
]);

export const productionBatches = pgTable("production_batches", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  supplierId: uuid("supplier_id").notNull(),
  status: text("status").default("planned").notNull(),
  projectionVersion: integer("projection_version").default(1).notNull(),
  expectedCompletionAt: timestamp("expected_completion_at", { mode: "date", withTimezone: true }).notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_batches_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_batches_status_check", sql`${table.status} in ('planned','released','in_progress','completed','failed','cancel_requested','cancelled')`),
  check("production_batches_version_check", sql`${table.projectionVersion} > 0`),
  foreignKey({ columns: [table.tenantId, table.supplierId], foreignColumns: [fulfillmentSuppliers.tenantId, fulfillmentSuppliers.id], name: "production_batches_supplier_fk" }).onDelete("restrict"),
  uniqueIndex("production_batches_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_batches_idempotency_unique").on(table.tenantId, table.supplierId, table.idempotencyKey),
  index("production_batches_queue_idx").on(table.tenantId, table.status, table.expectedCompletionAt),
]);

export const productionBatchMembers = pgTable("production_batch_members", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  batchId: uuid("batch_id").notNull(),
  productionOrderId: uuid("production_order_id").notNull(),
  addedBy: uuid("added_by").references(() => users.id, { onDelete: "set null" }),
  addedAt: timestamp("added_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_batch_members_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  foreignKey({ columns: [table.tenantId, table.batchId], foreignColumns: [productionBatches.tenantId, productionBatches.id], name: "production_batch_members_batch_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.productionOrderId], foreignColumns: [productionOrders.tenantId, productionOrders.id], name: "production_batch_members_order_fk" }).onDelete("restrict"),
  uniqueIndex("production_batch_members_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_batch_members_order_unique").on(table.tenantId, table.productionOrderId),
  uniqueIndex("production_batch_members_pair_unique").on(table.tenantId, table.batchId, table.productionOrderId),
]);

export const productionBatchEvents = pgTable("production_batch_events", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  batchId: uuid("batch_id").notNull(),
  sequence: integer("sequence").notNull(),
  type: text("type").notNull(),
  externalEventId: text("external_event_id"),
  evidenceCode: text("evidence_code").notNull(),
  encryptedNote: text("encrypted_note"),
  actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).notNull(),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_batch_events_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_batch_events_sequence_check", sql`${table.sequence} > 0`),
  check("production_batch_events_type_check", sql`${table.type} in ('released','started','completed','failed','cancel_requested','cancelled')`),
  foreignKey({ columns: [table.tenantId, table.batchId], foreignColumns: [productionBatches.tenantId, productionBatches.id], name: "production_batch_events_batch_fk" }).onDelete("restrict"),
  uniqueIndex("production_batch_events_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_batch_events_sequence_unique").on(table.tenantId, table.batchId, table.sequence),
  uniqueIndex("production_batch_events_external_unique").on(table.tenantId, table.batchId, table.externalEventId),
]);

export const productionRecoveryEvents = pgTable("production_recovery_events", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  recoveryCaseId: uuid("recovery_case_id").notNull(),
  sequence: integer("sequence").notNull(),
  action: text("action").notNull(),
  fromStatus: text("from_status").notNull(),
  toStatus: text("to_status").notNull(),
  outcomeCode: text("outcome_code").notNull(),
  encryptedNote: text("encrypted_note"),
  externalReference: text("external_reference"),
  actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }),
  occurredAt: timestamp("occurred_at", { mode: "date", withTimezone: true }).notNull(),
  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_recovery_events_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_recovery_events_sequence_check", sql`${table.sequence} > 0`),
  check("production_recovery_events_action_check", sql`${table.action} in ('start','resolve','cancel')`),
  check("production_recovery_events_status_check", sql`${table.fromStatus} in ('open','in_progress','resolved','cancelled') and ${table.toStatus} in ('open','in_progress','resolved','cancelled')`),
  foreignKey({ columns: [table.tenantId, table.recoveryCaseId], foreignColumns: [productionRecoveryCases.tenantId, productionRecoveryCases.id], name: "production_recovery_events_case_fk" }).onDelete("restrict"),
  uniqueIndex("production_recovery_events_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("production_recovery_events_sequence_unique").on(table.tenantId, table.recoveryCaseId, table.sequence),
]);
