import type {
  ArtifactRelationType,
  PodModelPolicy,
  PodExportManifest,
  PodExportStatus,
  PodTaskParameterSnapshot,
  PodToolKey,
  OrderPersonalizationBatchItemStatus,
  OrderPersonalizationBatchStatus,
  OrderPersonalizationRenderTaskStatus,
  OrderPersonalizationRenderParameterSnapshot,
  OrderPersonalizationRenderTool,
  ProductionFileSnapshot,
  RightsAssessmentStatus,
  RightsRiskLevel,
  RightsSource,
  TemplateSourceInspectionSlot,
  TemplateSourceInspectionStatus,
  TemplateSourceInspectionWarning,
  TemplateCanvas,
  TemplateSlotGeometry,
  VisualIndexStatus,
} from "@yummyai/contracts";
import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { assetFiles } from "./assets.js";
import { skus } from "./catalog.js";
import { designTasks, designVersions } from "./design.js";
import { organizations, users } from "./identity.js";
import { listingVersions } from "./listing.js";
import { orderCustomizationVersions } from "./order-customization.js";
import { orderLines, orders } from "./order.js";
import { podArtworkTasks } from "./pod.js";

export const designRecipeVersions = pgTable("design_recipe_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  recipeId: uuid("recipe_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  toolKey: text("tool_key").$type<PodToolKey>().notNull(),
  parameterSnapshot: jsonb("parameter_snapshot").$type<PodTaskParameterSnapshot>().notNull(),
  modelPolicy: jsonb("model_policy").$type<PodModelPolicy>().notNull(),
  promptTemplateVersion: text("prompt_template_version"),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("design_recipe_versions_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("design_recipe_versions_recipe_uuidv7_check", sql`substring(${table.recipeId}::text from 15 for 1) = '7'`),
  check("design_recipe_versions_number_check", sql`${table.versionNumber} > 0`),
  uniqueIndex("design_recipe_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("design_recipe_versions_number_unique").on(table.tenantId, table.recipeId, table.versionNumber),
  index("design_recipe_versions_tool_idx").on(table.tenantId, table.toolKey, table.createdAt),
]);

export const artifactRelations = pgTable("artifact_relations", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  fromAssetId: uuid("from_asset_id").notNull(),
  fromAssetVersion: integer("from_asset_version").notNull(),
  toAssetId: uuid("to_asset_id").notNull(),
  toAssetVersion: integer("to_asset_version").notNull(),
  relationType: text("relation_type").$type<ArtifactRelationType>().notNull(),
  taskId: uuid("task_id"),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("artifact_relations_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("artifact_relations_version_check", sql`${table.fromAssetVersion} > 0 and ${table.toAssetVersion} > 0`),
  check("artifact_relations_type_check", sql`${table.relationType} in ('source_to_result','result_to_derivative','result_to_listing','result_to_template','result_to_production')`),
  check("artifact_relations_distinct_check", sql`${table.fromAssetId} <> ${table.toAssetId} or ${table.fromAssetVersion} <> ${table.toAssetVersion}`),
  foreignKey({ columns: [table.tenantId, table.fromAssetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "artifact_relations_from_asset_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.toAssetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "artifact_relations_to_asset_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.taskId], foreignColumns: [podArtworkTasks.tenantId, podArtworkTasks.id], name: "artifact_relations_task_fk" }).onDelete("restrict"),
  uniqueIndex("artifact_relations_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("artifact_relations_edge_unique").on(table.tenantId, table.fromAssetId, table.fromAssetVersion, table.toAssetId, table.toAssetVersion, table.relationType),
  index("artifact_relations_from_idx").on(table.tenantId, table.fromAssetId, table.fromAssetVersion),
  index("artifact_relations_to_idx").on(table.tenantId, table.toAssetId, table.toAssetVersion),
]);

export const rightsAssessments = pgTable("rights_assessments", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  assetId: uuid("asset_id").notNull(),
  assetVersion: integer("asset_version").notNull(),
  taskId: uuid("task_id"),
  supersedesAssessmentId: uuid("supersedes_assessment_id"),
  rightsSource: jsonb("rights_source").$type<RightsSource>(),
  scopeSnapshot: jsonb("scope_snapshot").$type<Record<string, unknown>>().notNull(),
  status: text("status").$type<RightsAssessmentStatus>().notNull(),
  legalRisk: text("legal_risk").$type<RightsRiskLevel>().notNull(),
  visualSimilarityPermille: integer("visual_similarity_permille"),
  evidenceSnapshot: jsonb("evidence_snapshot").$type<Array<Record<string, unknown>>>().notNull(),
  modelKey: text("model_key"),
  modelVersion: text("model_version"),
  decisionReason: text("decision_reason"),
  assessedBy: uuid("assessed_by").references(() => users.id, { onDelete: "set null" }),
  assessedAt: timestamp("assessed_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("rights_assessments_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("rights_assessments_version_check", sql`${table.assetVersion} > 0`),
  check("rights_assessments_status_check", sql`${table.status} in ('pending','review_required','approved','blocked','rejected')`),
  check("rights_assessments_legal_risk_check", sql`${table.legalRisk} in ('unknown','low','medium','high')`),
  check("rights_assessments_visual_score_check", sql`${table.visualSimilarityPermille} is null or ${table.visualSimilarityPermille} between 0 and 1000`),
  check("rights_assessments_high_risk_check", sql`${table.legalRisk} <> 'high' or ${table.status} in ('blocked','rejected')`),
  check("rights_assessments_approval_check", sql`${table.status} <> 'approved' or ${table.legalRisk} = 'low'`),
  foreignKey({ columns: [table.tenantId, table.assetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "rights_assessments_asset_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.taskId], foreignColumns: [podArtworkTasks.tenantId, podArtworkTasks.id], name: "rights_assessments_task_fk" }).onDelete("restrict"),
  uniqueIndex("rights_assessments_tenant_id_unique").on(table.tenantId, table.id),
  index("rights_assessments_asset_idx").on(table.tenantId, table.assetId, table.assetVersion, table.assessedAt),
  index("rights_assessments_status_idx").on(table.tenantId, table.status, table.legalRisk, table.assessedAt),
]);

export const visualFingerprints = pgTable("visual_fingerprints", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  assetId: uuid("asset_id").notNull(),
  assetVersion: integer("asset_version").notNull(),
  checksumSha256: text("checksum_sha256").notNull(),
  perceptualHash: text("perceptual_hash"),
  fingerprintAlgorithm: text("fingerprint_algorithm").notNull(),
  fingerprintVersion: text("fingerprint_version").notNull(),
  indexStatus: text("index_status").$type<VisualIndexStatus>().notNull(),
  vectorIndexReference: text("vector_index_reference"),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  removedAt: timestamp("removed_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("visual_fingerprints_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("visual_fingerprints_version_check", sql`${table.assetVersion} > 0`),
  check("visual_fingerprints_checksum_check", sql`${table.checksumSha256} ~ '^[0-9a-f]{64}$'`),
  check("visual_fingerprints_phash_check", sql`${table.perceptualHash} is null or ${table.perceptualHash} ~ '^[0-9a-f]{16,128}$'`),
  check("visual_fingerprints_status_check", sql`${table.indexStatus} in ('pending','indexed','failed','removed')`),
  foreignKey({ columns: [table.tenantId, table.assetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "visual_fingerprints_asset_fk" }).onDelete("restrict"),
  uniqueIndex("visual_fingerprints_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("visual_fingerprints_asset_algorithm_unique").on(table.tenantId, table.assetId, table.assetVersion, table.fingerprintAlgorithm, table.fingerprintVersion),
  index("visual_fingerprints_checksum_idx").on(table.tenantId, table.checksumSha256),
  index("visual_fingerprints_status_idx").on(table.tenantId, table.indexStatus, table.createdAt),
]);

export const personalizationTemplateSourceInspections = pgTable("personalization_template_source_inspections", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  sourceAssetId: uuid("source_asset_id").notNull(),
  sourceAssetVersion: integer("source_asset_version").notNull(),
  checksumSha256: text("checksum_sha256").notNull(),
  source: text("source").$type<"png" | "psd">().notNull(),
  assetDomain: text("asset_domain").notNull(),
  rightsStatus: text("rights_status").notNull(),
  rightsSourceKind: text("rights_source_kind"),
  idempotencyKey: uuid("idempotency_key").notNull(),
  status: text("status").$type<TemplateSourceInspectionStatus>().default("queued").notNull(),
  parserKey: text("parser_key").notNull(),
  parserVersion: text("parser_version").notNull(),
  canvas: jsonb("canvas").$type<TemplateCanvas>(),
  slotSnapshot: jsonb("slot_snapshot").$type<TemplateSourceInspectionSlot[]>().default([]).notNull(),
  warningSnapshot: jsonb("warning_snapshot").$type<TemplateSourceInspectionWarning[]>().default([]).notNull(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  requestedBy: uuid("requested_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  startedAt: timestamp("started_at", { mode: "date", withTimezone: true }),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("personalization_template_source_inspections_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("personalization_template_source_inspections_version_check", sql`${table.sourceAssetVersion} > 0`),
  check("personalization_template_source_inspections_checksum_check", sql`${table.checksumSha256} ~ '^[0-9a-f]{64}$'`),
  check("personalization_template_source_inspections_source_check", sql`${table.source} in ('png','psd')`),
  check("personalization_template_source_inspections_domain_check", sql`${table.assetDomain} = 'authorized'`),
  check("personalization_template_source_inspections_rights_check", sql`${table.rightsStatus} = 'approved'`),
  check("personalization_template_source_inspections_status_check", sql`${table.status} in ('queued','running','completed','failed')`),
  check("personalization_template_source_inspections_complete_check", sql`${table.status} <> 'completed' or (${table.canvas} is not null and ${table.completedAt} is not null)`),
  check("personalization_template_source_inspections_failed_check", sql`${table.status} <> 'failed' or (${table.errorCode} is not null and ${table.errorMessage} is not null and ${table.completedAt} is not null)`),
  foreignKey({ columns: [table.tenantId, table.sourceAssetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "personalization_template_source_inspections_asset_fk" }).onDelete("restrict"),
  uniqueIndex("personalization_template_source_inspections_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("personalization_template_source_inspections_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("personalization_template_source_inspections_status_idx").on(table.tenantId, table.status, table.createdAt),
  index("personalization_template_source_inspections_asset_idx").on(table.tenantId, table.sourceAssetId, table.sourceAssetVersion, table.createdAt),
]);

export const personalizationTemplateVersions = pgTable("personalization_template_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  templateId: uuid("template_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  name: text("name").notNull(),
  source: text("source").notNull(),
  sourceAssetId: uuid("source_asset_id"),
  sourceAssetVersion: integer("source_asset_version"),
  sourceInspectionId: uuid("source_inspection_id"),
  sourceTemplateVersionId: uuid("source_template_version_id"),
  canvas: jsonb("canvas").$type<TemplateCanvas>().notNull(),
  previewAssetId: uuid("preview_asset_id"),
  status: text("status").default("draft").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("personalization_template_versions_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("personalization_template_versions_template_uuidv7_check", sql`substring(${table.templateId}::text from 15 for 1) = '7'`),
  check("personalization_template_versions_number_check", sql`${table.versionNumber} > 0`),
  check("personalization_template_versions_source_check", sql`${table.source} in ('blank','png','psd','popular_template')`),
  check("personalization_template_versions_status_check", sql`${table.status} in ('draft','pending_review','approved','rejected','archived')`),
  check("personalization_template_versions_source_asset_check", sql`${table.source} not in ('png','psd') or (${table.sourceAssetId} is not null and ${table.sourceAssetVersion} > 0)`),
  check("personalization_template_versions_source_template_check", sql`(${table.source} = 'popular_template' and ${table.sourceTemplateVersionId} is not null and ${table.sourceTemplateVersionId} <> ${table.id}) or (${table.source} <> 'popular_template' and ${table.sourceTemplateVersionId} is null)`),
  foreignKey({ columns: [table.tenantId, table.sourceAssetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "personalization_template_versions_source_asset_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.sourceInspectionId], foreignColumns: [personalizationTemplateSourceInspections.tenantId, personalizationTemplateSourceInspections.id], name: "personalization_template_versions_source_inspection_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.sourceTemplateVersionId], foreignColumns: [table.tenantId, table.id], name: "personalization_template_versions_source_template_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.previewAssetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "personalization_template_versions_preview_asset_fk" }).onDelete("restrict"),
  uniqueIndex("personalization_template_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("personalization_template_versions_number_unique").on(table.tenantId, table.templateId, table.versionNumber),
  uniqueIndex("personalization_template_versions_source_inspection_unique").on(table.tenantId, table.sourceInspectionId),
  index("personalization_template_versions_status_idx").on(table.tenantId, table.status, table.createdAt),
  index("personalization_template_versions_source_template_idx").on(table.tenantId, table.sourceTemplateVersionId),
]);

export const templateSlots = pgTable("template_slots", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  templateVersionId: uuid("template_version_id").notNull(),
  stableKey: text("stable_key").notNull(),
  name: text("name").notNull(),
  kind: text("kind").notNull(),
  psdGroup: text("psd_group"),
  geometry: jsonb("geometry").$type<TemplateSlotGeometry>().notNull(),
  fillMode: text("fill_mode").notNull(),
  validationSnapshot: jsonb("validation_snapshot").$type<Record<string, unknown>>().notNull(),
  replaceable: boolean("replaceable").notNull(),
  reuseLabel: text("reuse_label"),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("template_slots_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("template_slots_kind_check", sql`${table.kind} in ('image','text','decoration','background')`),
  check("template_slots_psd_group_check", sql`${table.psdGroup} is null or ${table.psdGroup} in ('image','text','decoration','background')`),
  check("template_slots_fill_mode_check", sql`${table.fillMode} in ('contain','cover','stretch','tile','none')`),
  foreignKey({ columns: [table.tenantId, table.templateVersionId], foreignColumns: [personalizationTemplateVersions.tenantId, personalizationTemplateVersions.id], name: "template_slots_template_fk" }).onDelete("cascade"),
  uniqueIndex("template_slots_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("template_slots_stable_key_unique").on(table.tenantId, table.templateVersionId, table.stableKey),
  index("template_slots_reuse_idx").on(table.tenantId, table.templateVersionId, table.reuseLabel),
]);

export const skuTemplateBindings = pgTable("sku_template_bindings", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  skuId: uuid("sku_id").notNull(),
  templateVersionId: uuid("template_version_id").notNull(),
  sizeLabel: text("size_label").notNull(),
  mappingSnapshot: jsonb("mapping_snapshot").$type<Record<string, unknown>>().notNull(),
  status: text("status").default("active").notNull(),
  effectiveFrom: timestamp("effective_from", { mode: "date", withTimezone: true }).notNull(),
  effectiveTo: timestamp("effective_to", { mode: "date", withTimezone: true }),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("sku_template_bindings_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("sku_template_bindings_status_check", sql`${table.status} in ('active','inactive')`),
  check("sku_template_bindings_effective_check", sql`${table.effectiveTo} is null or ${table.effectiveTo} > ${table.effectiveFrom}`),
  foreignKey({ columns: [table.tenantId, table.skuId], foreignColumns: [skus.tenantId, skus.id], name: "sku_template_bindings_sku_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.templateVersionId], foreignColumns: [personalizationTemplateVersions.tenantId, personalizationTemplateVersions.id], name: "sku_template_bindings_template_fk" }).onDelete("restrict"),
  uniqueIndex("sku_template_bindings_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("sku_template_bindings_version_size_unique").on(table.tenantId, table.skuId, table.templateVersionId, table.sizeLabel),
  index("sku_template_bindings_lookup_idx").on(table.tenantId, table.skuId, table.status, table.effectiveFrom),
]);

export const orderPersonalizationBatches = pgTable("order_personalization_batches", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  idempotencyKey: uuid("idempotency_key").notNull(),
  requestChecksum: text("request_checksum").notNull(),
  status: text("status").$type<OrderPersonalizationBatchStatus>().default("queued").notNull(),
  itemCount: integer("item_count").notNull(),
  preparedCount: integer("prepared_count").default(0).notNull(),
  failedCount: integer("failed_count").default(0).notNull(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  requestedBy: uuid("requested_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  startedAt: timestamp("started_at", { mode: "date", withTimezone: true }),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("order_personalization_batches_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("order_personalization_batches_idempotency_uuidv7_check", sql`substring(${table.idempotencyKey}::text from 15 for 1) = '7'`),
  check("order_personalization_batches_checksum_check", sql`${table.requestChecksum} ~ '^[0-9a-f]{64}$'`),
  check("order_personalization_batches_status_check", sql`${table.status} in ('queued','running','completed','partially_succeeded','failed')`),
  check("order_personalization_batches_count_check", sql`${table.itemCount} between 1 and 100 and ${table.preparedCount} >= 0 and ${table.failedCount} >= 0 and ${table.preparedCount} + ${table.failedCount} <= ${table.itemCount}`),
  check("order_personalization_batches_terminal_check", sql`
    (${table.status} = 'completed' and ${table.preparedCount} = ${table.itemCount} and ${table.failedCount} = 0 and ${table.completedAt} is not null)
    or (${table.status} = 'partially_succeeded' and ${table.preparedCount} > 0 and ${table.failedCount} > 0 and ${table.preparedCount} + ${table.failedCount} = ${table.itemCount} and ${table.completedAt} is not null)
    or (${table.status} = 'failed' and ${table.failedCount} = ${table.itemCount} and ${table.completedAt} is not null)
    or ${table.status} in ('queued','running')
  `),
  uniqueIndex("order_personalization_batches_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("order_personalization_batches_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("order_personalization_batches_status_idx").on(table.tenantId, table.status, table.createdAt),
]);

export const orderPersonalizationBatchItems = pgTable("order_personalization_batch_items", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  batchId: uuid("batch_id").notNull(),
  ordinal: integer("ordinal").notNull(),
  orderId: uuid("order_id").notNull(),
  orderLineId: uuid("order_line_id").notNull(),
  customizationVersionId: uuid("customization_version_id").notNull(),
  bindingId: uuid("binding_id").notNull(),
  templateVersionId: uuid("template_version_id"),
  status: text("status").$type<OrderPersonalizationBatchItemStatus>().default("queued").notNull(),
  encryptedResolution: text("encrypted_resolution"),
  resolutionChecksum: text("resolution_checksum"),
  resolvedSlotCount: integer("resolved_slot_count").default(0).notNull(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  startedAt: timestamp("started_at", { mode: "date", withTimezone: true }),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("order_personalization_batch_items_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("order_personalization_batch_items_ordinal_check", sql`${table.ordinal} between 0 and 99`),
  check("order_personalization_batch_items_status_check", sql`${table.status} in ('queued','running','prepared','failed')`),
  check("order_personalization_batch_items_slot_count_check", sql`${table.resolvedSlotCount} between 0 and 500`),
  check("order_personalization_batch_items_resolution_checksum_check", sql`${table.resolutionChecksum} is null or ${table.resolutionChecksum} ~ '^[0-9a-f]{64}$'`),
  check("order_personalization_batch_items_prepared_check", sql`${table.status} <> 'prepared' or (${table.templateVersionId} is not null and ${table.encryptedResolution} is not null and ${table.resolutionChecksum} is not null and ${table.completedAt} is not null)`),
  check("order_personalization_batch_items_failed_check", sql`${table.status} <> 'failed' or (${table.errorCode} is not null and ${table.errorMessage} is not null and ${table.completedAt} is not null)`),
  foreignKey({ columns: [table.tenantId, table.batchId], foreignColumns: [orderPersonalizationBatches.tenantId, orderPersonalizationBatches.id], name: "order_personalization_batch_items_batch_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.orderId], foreignColumns: [orders.tenantId, orders.id], name: "order_personalization_batch_items_order_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.orderLineId], foreignColumns: [orderLines.tenantId, orderLines.id], name: "order_personalization_batch_items_order_line_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.customizationVersionId], foreignColumns: [orderCustomizationVersions.tenantId, orderCustomizationVersions.id], name: "order_personalization_batch_items_customization_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.bindingId], foreignColumns: [skuTemplateBindings.tenantId, skuTemplateBindings.id], name: "order_personalization_batch_items_binding_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.templateVersionId], foreignColumns: [personalizationTemplateVersions.tenantId, personalizationTemplateVersions.id], name: "order_personalization_batch_items_template_fk" }).onDelete("restrict"),
  uniqueIndex("order_personalization_batch_items_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("order_personalization_batch_items_ordinal_unique").on(table.tenantId, table.batchId, table.ordinal),
  uniqueIndex("order_personalization_batch_items_order_line_unique").on(table.tenantId, table.batchId, table.orderLineId),
  index("order_personalization_batch_items_status_idx").on(table.tenantId, table.batchId, table.status, table.ordinal),
]);

export const orderPersonalizationRenderTasks = pgTable("order_personalization_render_tasks", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  batchItemId: uuid("batch_item_id").notNull(),
  designTaskId: uuid("design_task_id").notNull(),
  toolKey: text("tool_key").$type<OrderPersonalizationRenderTool>().notNull(),
  status: text("status").$type<OrderPersonalizationRenderTaskStatus>().default("queued").notNull(),
  parameterSnapshot: jsonb("parameter_snapshot").$type<OrderPersonalizationRenderParameterSnapshot>().notNull(),
  requestChecksum: text("request_checksum").notNull(),
  idempotencyKey: uuid("idempotency_key").notNull(),
  progressPercent: integer("progress_percent").default(0).notNull(),
  attemptCount: integer("attempt_count").default(0).notNull(),
  maxAttempts: integer("max_attempts").default(3).notNull(),
  resultVersionId: uuid("result_version_id"),
  modelKey: text("model_key"),
  modelVersion: text("model_version"),
  seed: text("seed"),
  qualityCheckSnapshot: jsonb("quality_check_snapshot").$type<Record<string, unknown>>(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  requestedBy: uuid("requested_by").references(() => users.id, { onDelete: "set null" }),
  startedAt: timestamp("started_at", { mode: "date", withTimezone: true }),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("order_personalization_render_tasks_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("order_personalization_render_tasks_idempotency_uuidv7_check", sql`substring(${table.idempotencyKey}::text from 15 for 1) = '7'`),
  check("order_personalization_render_tasks_tool_check", sql`${table.toolKey} in ('image_composite','group_photo','pet_outfit','fulfillment_composite','vector_fulfillment')`),
  check("order_personalization_render_tasks_status_check", sql`${table.status} in ('queued','running','awaiting_review','partially_succeeded','failed')`),
  check("order_personalization_render_tasks_checksum_check", sql`${table.requestChecksum} ~ '^[0-9a-f]{64}$'`),
  check("order_personalization_render_tasks_progress_check", sql`${table.progressPercent} between 0 and 100`),
  check("order_personalization_render_tasks_attempt_check", sql`${table.attemptCount} >= 0 and ${table.maxAttempts} between 1 and 20 and ${table.attemptCount} <= ${table.maxAttempts}`),
  check("order_personalization_render_tasks_result_check", sql`${table.status} not in ('awaiting_review','partially_succeeded') or (${table.resultVersionId} is not null and ${table.completedAt} is not null)`),
  check("order_personalization_render_tasks_failure_check", sql`${table.status} <> 'failed' or (${table.errorCode} is not null and ${table.errorMessage} is not null and ${table.completedAt} is not null)`),
  foreignKey({ columns: [table.tenantId, table.batchItemId], foreignColumns: [orderPersonalizationBatchItems.tenantId, orderPersonalizationBatchItems.id], name: "order_personalization_render_tasks_batch_item_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.designTaskId], foreignColumns: [designTasks.tenantId, designTasks.id], name: "order_personalization_render_tasks_design_task_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.resultVersionId], foreignColumns: [designVersions.tenantId, designVersions.id], name: "order_personalization_render_tasks_result_version_fk" }).onDelete("restrict"),
  uniqueIndex("order_personalization_render_tasks_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("order_personalization_render_tasks_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("order_personalization_render_tasks_item_idx").on(table.tenantId, table.batchItemId, table.createdAt),
  index("order_personalization_render_tasks_status_idx").on(table.tenantId, table.status, table.updatedAt),
]);

export const listingArtifactBindings = pgTable("listing_artifact_bindings", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  listingVersionId: uuid("listing_version_id").notNull(),
  assetId: uuid("asset_id").notNull(),
  assetVersion: integer("asset_version").notNull(),
  contentKind: text("content_kind").notNull(),
  slotKey: text("slot_key").notNull(),
  status: text("status").default("candidate").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("listing_artifact_bindings_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("listing_artifact_bindings_version_check", sql`${table.assetVersion} > 0`),
  check("listing_artifact_bindings_kind_check", sql`${table.contentKind} in ('image','title')`),
  check("listing_artifact_bindings_status_check", sql`${table.status} in ('candidate','approved','rejected')`),
  foreignKey({ columns: [table.tenantId, table.listingVersionId], foreignColumns: [listingVersions.tenantId, listingVersions.id], name: "listing_artifact_bindings_listing_version_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.assetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "listing_artifact_bindings_asset_fk" }).onDelete("restrict"),
  uniqueIndex("listing_artifact_bindings_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("listing_artifact_bindings_slot_unique").on(table.tenantId, table.listingVersionId, table.contentKind, table.slotKey),
  index("listing_artifact_bindings_asset_idx").on(table.tenantId, table.assetId, table.assetVersion),
]);

export const podExportPackages = pgTable("pod_export_packages", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  taskId: uuid("task_id").notNull(),
  designVersionId: uuid("design_version_id").notNull(),
  status: text("status").$type<PodExportStatus>().default("queued").notNull(),
  idempotencyKey: uuid("idempotency_key").notNull(),
  objectKey: text("object_key"),
  checksumSha256: text("checksum_sha256"),
  byteSize: bigint("byte_size", { mode: "number" }),
  manifest: jsonb("manifest").$type<PodExportManifest>(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  requestedBy: uuid("requested_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("pod_export_packages_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("pod_export_packages_idempotency_uuidv7_check", sql`substring(${table.idempotencyKey}::text from 15 for 1) = '7'`),
  check("pod_export_packages_status_check", sql`${table.status} in ('queued','running','completed','failed')`),
  check("pod_export_packages_checksum_check", sql`${table.checksumSha256} is null or ${table.checksumSha256} ~ '^[0-9a-f]{64}$'`),
  check("pod_export_packages_byte_size_check", sql`${table.byteSize} is null or ${table.byteSize} >= 0`),
  check("pod_export_packages_complete_check", sql`${table.status} <> 'completed' or (${table.objectKey} is not null and ${table.checksumSha256} is not null and ${table.byteSize} is not null and ${table.manifest} is not null and ${table.completedAt} is not null)`),
  foreignKey({ columns: [table.tenantId, table.taskId], foreignColumns: [podArtworkTasks.tenantId, podArtworkTasks.id], name: "pod_export_packages_task_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.designVersionId], foreignColumns: [designVersions.tenantId, designVersions.id], name: "pod_export_packages_design_version_fk" }).onDelete("restrict"),
  uniqueIndex("pod_export_packages_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("pod_export_packages_idempotency_unique").on(table.tenantId, table.idempotencyKey),
  index("pod_export_packages_task_idx").on(table.tenantId, table.taskId, table.createdAt),
]);

export const productionManifests = pgTable("production_manifests", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  orderLineId: uuid("order_line_id"),
  designVersionId: uuid("design_version_id"),
  templateVersionId: uuid("template_version_id"),
  inputSnapshot: jsonb("input_snapshot").$type<Array<{ assetId: string; assetVersion: number; checksumSha256: string }>>().notNull(),
  fileSnapshot: jsonb("file_snapshot").$type<ProductionFileSnapshot[]>().notNull(),
  qualityCheckSnapshot: jsonb("quality_check_snapshot").$type<Record<string, unknown>>().notNull(),
  status: text("status").default("pending_review").notNull(),
  reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { mode: "date", withTimezone: true }),
  rejectionReason: text("rejection_reason"),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("production_manifests_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("production_manifests_source_check", sql`${table.orderLineId} is not null or ${table.designVersionId} is not null`),
  check("production_manifests_status_check", sql`${table.status} in ('pending_review','approved','rejected')`),
  check("production_manifests_rejection_check", sql`${table.status} <> 'rejected' or length(${table.rejectionReason}) > 0`),
  foreignKey({ columns: [table.tenantId, table.orderLineId], foreignColumns: [orderLines.tenantId, orderLines.id], name: "production_manifests_order_line_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.designVersionId], foreignColumns: [designVersions.tenantId, designVersions.id], name: "production_manifests_design_version_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.templateVersionId], foreignColumns: [personalizationTemplateVersions.tenantId, personalizationTemplateVersions.id], name: "production_manifests_template_version_fk" }).onDelete("restrict"),
  uniqueIndex("production_manifests_tenant_id_unique").on(table.tenantId, table.id),
  index("production_manifests_status_idx").on(table.tenantId, table.status, table.createdAt),
  index("production_manifests_order_line_idx").on(table.tenantId, table.orderLineId, table.createdAt),
]);
