import type {
  CanvasPhysicalSize,
  CanvasWrapMode,
  CreativeDesignCandidateStatus,
  CreativeDesignVersionStatus,
  MockupOutputStatus,
  MockupTemplateCompilation,
  MockupTemplateInspectionStatus,
  MockupTemplatePackStatus,
  PodBatchStatus,
} from "@yummyai/contracts";
import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { assetFiles } from "./assets.js";
import { skus } from "./catalog.js";
import { designTasks, designVersions } from "./design.js";
import { organizations, users } from "./identity.js";
import { designRecipeVersions } from "./pod-governance.js";

type FocalPoint = { xPermille: number; yPermille: number };
type PinnedAsset = { assetId: string; assetVersion: number; checksumSha256: string };
type GeneratedRegion = { x: number; y: number; width: number; height: number };
type MockupWarning = { code: string; message: string };

export const canvasPrintSpecVersions = pgTable("canvas_print_spec_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  specId: uuid("spec_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  name: text("name").notNull(),
  aspectWidth: integer("aspect_width").notNull(),
  aspectHeight: integer("aspect_height").notNull(),
  targetDpi: integer("target_dpi").notNull(),
  bleedMm: numeric("bleed_mm", { precision: 10, scale: 3 }).notNull(),
  safeZoneMm: numeric("safe_zone_mm", { precision: 10, scale: 3 }).notNull(),
  wrapMode: text("wrap_mode").$type<CanvasWrapMode>().notNull(),
  physicalSizes: jsonb("physical_sizes").$type<CanvasPhysicalSize[]>().notNull(),
  status: text("status").default("draft").notNull(),
  rejectionReason: text("rejection_reason"),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { mode: "date", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("canvas_print_spec_versions_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("canvas_print_spec_versions_spec_uuidv7_check", sql`substring(${table.specId}::text from 15 for 1) = '7'`),
  check("canvas_print_spec_versions_number_check", sql`${table.versionNumber} > 0`),
  check("canvas_print_spec_versions_aspect_check", sql`${table.aspectWidth} between 1 and 100 and ${table.aspectHeight} between 1 and 100`),
  check("canvas_print_spec_versions_dpi_check", sql`${table.targetDpi} between 72 and 2400`),
  check("canvas_print_spec_versions_wrap_check", sql`${table.wrapMode} in ('none','mirror','extend','solid')`),
  check("canvas_print_spec_versions_status_check", sql`${table.status} in ('draft','approved','rejected','archived')`),
  check("canvas_print_spec_versions_rejection_check", sql`${table.status} <> 'rejected' or length(${table.rejectionReason}) > 0`),
  uniqueIndex("canvas_print_spec_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("canvas_print_spec_versions_number_unique").on(table.tenantId, table.specId, table.versionNumber),
  index("canvas_print_spec_versions_status_idx").on(table.tenantId, table.status, table.createdAt),
]);

export const creativeDesignBatches = pgTable("creative_design_batches", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  recipeVersionId: uuid("recipe_version_id"),
  status: text("status").$type<PodBatchStatus>().default("queued").notNull(),
  itemCount: integer("item_count").notNull(),
  generatedCount: integer("generated_count").default(0).notNull(),
  approvedCount: integer("approved_count").default(0).notNull(),
  failedCount: integer("failed_count").default(0).notNull(),
  requestChecksum: text("request_checksum").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("creative_design_batches_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("creative_design_batches_status_check", sql`${table.status} in ('queued','running','awaiting_review','partially_succeeded','completed','failed','cancelled')`),
  check("creative_design_batches_count_check", sql`${table.itemCount} between 1 and 50 and ${table.generatedCount} between 0 and 200 and ${table.approvedCount} between 0 and 200 and ${table.failedCount} between 0 and ${table.itemCount}`),
  check("creative_design_batches_checksum_check", sql`${table.requestChecksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({ columns: [table.tenantId, table.recipeVersionId], foreignColumns: [designRecipeVersions.tenantId, designRecipeVersions.id], name: "creative_design_batches_recipe_fk" }).onDelete("restrict"),
  uniqueIndex("creative_design_batches_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("creative_design_batches_checksum_unique").on(table.tenantId, table.requestChecksum),
  index("creative_design_batches_status_idx").on(table.tenantId, table.status, table.updatedAt),
]);

export const creativeDesignBatchItems = pgTable("creative_design_batch_items", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  batchId: uuid("batch_id").notNull(),
  ordinal: integer("ordinal").notNull(),
  rowKey: text("row_key").notNull(),
  name: text("name").notNull(),
  prompt: text("prompt").notNull(),
  negativePrompt: text("negative_prompt"),
  referenceSnapshot: jsonb("reference_snapshot").$type<PinnedAsset[]>().default([]).notNull(),
  candidateCount: integer("candidate_count").notNull(),
  printSpecVersionIds: jsonb("print_spec_version_ids").$type<string[]>().notNull(),
  focalPoint: jsonb("focal_point").$type<FocalPoint>().notNull(),
  status: text("status").$type<PodBatchStatus>().default("queued").notNull(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("creative_design_batch_items_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("creative_design_batch_items_ordinal_check", sql`${table.ordinal} between 0 and 49`),
  check("creative_design_batch_items_candidate_check", sql`${table.candidateCount} between 1 and 4`),
  check("creative_design_batch_items_status_check", sql`${table.status} in ('queued','running','awaiting_review','partially_succeeded','completed','failed','cancelled')`),
  foreignKey({ columns: [table.tenantId, table.batchId], foreignColumns: [creativeDesignBatches.tenantId, creativeDesignBatches.id], name: "creative_design_batch_items_batch_fk" }).onDelete("restrict"),
  uniqueIndex("creative_design_batch_items_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("creative_design_batch_items_row_unique").on(table.tenantId, table.batchId, table.rowKey),
  uniqueIndex("creative_design_batch_items_ordinal_unique").on(table.tenantId, table.batchId, table.ordinal),
  index("creative_design_batch_items_status_idx").on(table.tenantId, table.batchId, table.status, table.ordinal),
]);

export const creativeDesignCandidates = pgTable("creative_design_candidates", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  itemId: uuid("item_id").notNull(),
  ordinal: integer("ordinal").notNull(),
  status: text("status").$type<CreativeDesignCandidateStatus>().default("queued").notNull(),
  assetId: uuid("asset_id"),
  assetVersion: integer("asset_version"),
  checksumSha256: text("checksum_sha256"),
  modelKey: text("model_key"),
  modelVersion: text("model_version"),
  promptTemplateVersion: text("prompt_template_version"),
  parameterSnapshot: jsonb("parameter_snapshot").$type<Record<string, unknown>>().notNull(),
  inputChecksum: text("input_checksum").notNull(),
  seed: text("seed"),
  costUsd: numeric("cost_usd", { precision: 12, scale: 6 }),
  qualitySnapshot: jsonb("quality_snapshot").$type<Record<string, unknown>>(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("creative_design_candidates_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("creative_design_candidates_ordinal_check", sql`${table.ordinal} between 0 and 3`),
  check("creative_design_candidates_status_check", sql`${table.status} in ('queued','running','generated','selected','failed','cancelled')`),
  check("creative_design_candidates_asset_version_check", sql`${table.assetVersion} is null or ${table.assetVersion} > 0`),
  check("creative_design_candidates_checksum_check", sql`${table.checksumSha256} is null or ${table.checksumSha256} ~ '^[0-9a-f]{64}$'`),
  check("creative_design_candidates_input_checksum_check", sql`${table.inputChecksum} ~ '^[0-9a-f]{64}$'`),
  check("creative_design_candidates_result_check", sql`${table.status} not in ('generated','selected') or (${table.assetId} is not null and ${table.assetVersion} is not null and ${table.checksumSha256} is not null and ${table.completedAt} is not null)`),
  check("creative_design_candidates_failure_check", sql`${table.status} <> 'failed' or (${table.errorCode} is not null and ${table.errorMessage} is not null and ${table.completedAt} is not null)`),
  foreignKey({ columns: [table.tenantId, table.itemId], foreignColumns: [creativeDesignBatchItems.tenantId, creativeDesignBatchItems.id], name: "creative_design_candidates_item_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.assetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "creative_design_candidates_asset_fk" }).onDelete("restrict"),
  uniqueIndex("creative_design_candidates_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("creative_design_candidates_ordinal_unique").on(table.tenantId, table.itemId, table.ordinal),
  index("creative_design_candidates_status_idx").on(table.tenantId, table.itemId, table.status),
]);

export const creativeDesignVersions = pgTable("creative_design_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  familyId: uuid("family_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  sourceCandidateId: uuid("source_candidate_id").notNull(),
  name: text("name").notNull(),
  status: text("status").$type<CreativeDesignVersionStatus>().default("adapting").notNull(),
  rejectionReason: text("rejection_reason"),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { mode: "date", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("creative_design_versions_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("creative_design_versions_family_uuidv7_check", sql`substring(${table.familyId}::text from 15 for 1) = '7'`),
  check("creative_design_versions_number_check", sql`${table.versionNumber} > 0`),
  check("creative_design_versions_status_check", sql`${table.status} in ('adapting','pending_review','approved','rejected')`),
  check("creative_design_versions_rejection_check", sql`${table.status} <> 'rejected' or length(${table.rejectionReason}) > 0`),
  foreignKey({ columns: [table.tenantId, table.sourceCandidateId], foreignColumns: [creativeDesignCandidates.tenantId, creativeDesignCandidates.id], name: "creative_design_versions_candidate_fk" }).onDelete("restrict"),
  uniqueIndex("creative_design_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("creative_design_versions_number_unique").on(table.tenantId, table.familyId, table.versionNumber),
  uniqueIndex("creative_design_versions_candidate_unique").on(table.tenantId, table.sourceCandidateId),
  index("creative_design_versions_status_idx").on(table.tenantId, table.status, table.createdAt),
]);

export const creativeDesignVersionAssets = pgTable("creative_design_version_assets", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  creativeDesignVersionId: uuid("creative_design_version_id").notNull(),
  assetId: uuid("asset_id").notNull(),
  assetVersion: integer("asset_version").notNull(),
  role: text("role").notNull(),
  printSpecVersionId: uuid("print_spec_version_id"),
  adaptationMode: text("adaptation_mode").notNull(),
  generatedRegions: jsonb("generated_regions").$type<GeneratedRegion[]>().default([]).notNull(),
  qualitySnapshot: jsonb("quality_snapshot").$type<Record<string, unknown>>(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("creative_design_version_assets_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("creative_design_version_assets_version_check", sql`${table.assetVersion} > 0`),
  check("creative_design_version_assets_role_check", sql`${table.role} in ('master','aspect_variant')`),
  check("creative_design_version_assets_mode_check", sql`${table.adaptationMode} in ('original','crop','ai_outpaint')`),
  check("creative_design_version_assets_spec_check", sql`(${table.role} = 'master' and ${table.printSpecVersionId} is null and ${table.adaptationMode} = 'original') or (${table.role} = 'aspect_variant' and ${table.printSpecVersionId} is not null and ${table.adaptationMode} in ('crop','ai_outpaint'))`),
  foreignKey({ columns: [table.tenantId, table.creativeDesignVersionId], foreignColumns: [creativeDesignVersions.tenantId, creativeDesignVersions.id], name: "creative_design_version_assets_version_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.assetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "creative_design_version_assets_asset_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.printSpecVersionId], foreignColumns: [canvasPrintSpecVersions.tenantId, canvasPrintSpecVersions.id], name: "creative_design_version_assets_spec_fk" }).onDelete("restrict"),
  uniqueIndex("creative_design_version_assets_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("creative_design_version_assets_pair_unique").on(table.tenantId, table.creativeDesignVersionId, table.assetId, table.assetVersion),
  uniqueIndex("creative_design_version_assets_spec_unique").on(table.tenantId, table.creativeDesignVersionId, table.printSpecVersionId),
  index("creative_design_version_assets_version_idx").on(table.tenantId, table.creativeDesignVersionId, table.role),
]);

export const creativeDesignSkuBindings = pgTable("creative_design_sku_bindings", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  creativeDesignVersionId: uuid("creative_design_version_id").notNull(),
  skuId: uuid("sku_id").notNull(),
  printSpecVersionId: uuid("print_spec_version_id").notNull(),
  designTaskId: uuid("design_task_id").notNull(),
  designVersionId: uuid("design_version_id").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("creative_design_sku_bindings_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  foreignKey({ columns: [table.tenantId, table.creativeDesignVersionId], foreignColumns: [creativeDesignVersions.tenantId, creativeDesignVersions.id], name: "creative_design_sku_bindings_creative_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.skuId], foreignColumns: [skus.tenantId, skus.id], name: "creative_design_sku_bindings_sku_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.printSpecVersionId], foreignColumns: [canvasPrintSpecVersions.tenantId, canvasPrintSpecVersions.id], name: "creative_design_sku_bindings_spec_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.designTaskId], foreignColumns: [designTasks.tenantId, designTasks.id], name: "creative_design_sku_bindings_task_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.designVersionId], foreignColumns: [designVersions.tenantId, designVersions.id], name: "creative_design_sku_bindings_version_fk" }).onDelete("restrict"),
  uniqueIndex("creative_design_sku_bindings_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("creative_design_sku_bindings_pair_unique").on(table.tenantId, table.creativeDesignVersionId, table.skuId, table.printSpecVersionId),
  uniqueIndex("creative_design_sku_bindings_design_version_unique").on(table.tenantId, table.designVersionId),
  index("creative_design_sku_bindings_sku_idx").on(table.tenantId, table.skuId, table.createdAt),
]);

export const mockupTemplateSourceInspections = pgTable("mockup_template_source_inspections", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  sourceAssetId: uuid("source_asset_id").notNull(),
  sourceAssetVersion: integer("source_asset_version").notNull(),
  checksumSha256: text("checksum_sha256").notNull(),
  slotKey: text("slot_key").notNull(),
  status: text("status").$type<MockupTemplateInspectionStatus>().default("queued").notNull(),
  compilerVersion: text("compiler_version").notNull(),
  compilation: jsonb("compilation").$type<MockupTemplateCompilation>(),
  warnings: jsonb("warnings").$type<MockupWarning[]>().default([]).notNull(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  requestedBy: uuid("requested_by").references(() => users.id, { onDelete: "set null" }),
  confirmedBy: uuid("confirmed_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  confirmedAt: timestamp("confirmed_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("mockup_template_source_inspections_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("mockup_template_source_inspections_version_check", sql`${table.sourceAssetVersion} > 0`),
  check("mockup_template_source_inspections_checksum_check", sql`${table.checksumSha256} ~ '^[0-9a-f]{64}$'`),
  check("mockup_template_source_inspections_slot_check", sql`${table.slotKey} ~ '^[a-z][a-z0-9_.-]{0,79}$'`),
  check("mockup_template_source_inspections_status_check", sql`${table.status} in ('queued','running','completed','failed')`),
  check("mockup_template_source_inspections_complete_check", sql`${table.status} <> 'completed' or (${table.compilation} is not null and ${table.completedAt} is not null)`),
  check("mockup_template_source_inspections_failure_check", sql`${table.status} <> 'failed' or (${table.errorCode} is not null and ${table.errorMessage} is not null and ${table.completedAt} is not null)`),
  check("mockup_template_source_inspections_confirmation_check", sql`${table.confirmedAt} is null or (${table.status} = 'completed' and ${table.confirmedBy} is not null)`),
  foreignKey({ columns: [table.tenantId, table.sourceAssetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "mockup_template_source_inspections_asset_fk" }).onDelete("restrict"),
  uniqueIndex("mockup_template_source_inspections_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("mockup_template_source_inspections_source_unique").on(table.tenantId, table.sourceAssetId, table.sourceAssetVersion, table.slotKey, table.compilerVersion),
  index("mockup_template_source_inspections_status_idx").on(table.tenantId, table.status, table.createdAt),
]);

export const mockupTemplatePackVersions = pgTable("mockup_template_pack_versions", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  packId: uuid("pack_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  name: text("name").notNull(),
  platform: text("platform").notNull(),
  locale: text("locale").notNull(),
  productCategory: text("product_category").default("canvas_art").notNull(),
  status: text("status").$type<MockupTemplatePackStatus>().default("draft").notNull(),
  rejectionReason: text("rejection_reason"),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { mode: "date", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("mockup_template_pack_versions_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("mockup_template_pack_versions_pack_uuidv7_check", sql`substring(${table.packId}::text from 15 for 1) = '7'`),
  check("mockup_template_pack_versions_number_check", sql`${table.versionNumber} > 0`),
  check("mockup_template_pack_versions_platform_check", sql`${table.platform} in ('amazon','etsy')`),
  check("mockup_template_pack_versions_locale_check", sql`${table.locale} ~ '^[a-z]{2}-[A-Z]{2}$'`),
  check("mockup_template_pack_versions_category_check", sql`${table.productCategory} = 'canvas_art'`),
  check("mockup_template_pack_versions_status_check", sql`${table.status} in ('draft','approved','rejected','archived')`),
  check("mockup_template_pack_versions_rejection_check", sql`${table.status} <> 'rejected' or length(${table.rejectionReason}) > 0`),
  uniqueIndex("mockup_template_pack_versions_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("mockup_template_pack_versions_number_unique").on(table.tenantId, table.packId, table.versionNumber),
  index("mockup_template_pack_versions_status_idx").on(table.tenantId, table.status, table.platform, table.locale),
]);

export const mockupTemplateSlots = pgTable("mockup_template_slots", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  templatePackVersionId: uuid("template_pack_version_id").notNull(),
  inspectionId: uuid("inspection_id").notNull(),
  slotKey: text("slot_key").notNull(),
  label: text("label").notNull(),
  ordinal: integer("ordinal").notNull(),
  required: boolean("required").notNull(),
  acceptedPrintSpecVersionIds: jsonb("accepted_print_spec_version_ids").$type<string[]>().notNull(),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("mockup_template_slots_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("mockup_template_slots_key_check", sql`${table.slotKey} ~ '^[a-z][a-z0-9_.-]{0,79}$'`),
  check("mockup_template_slots_ordinal_check", sql`${table.ordinal} between 0 and 15`),
  foreignKey({ columns: [table.tenantId, table.templatePackVersionId], foreignColumns: [mockupTemplatePackVersions.tenantId, mockupTemplatePackVersions.id], name: "mockup_template_slots_pack_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.inspectionId], foreignColumns: [mockupTemplateSourceInspections.tenantId, mockupTemplateSourceInspections.id], name: "mockup_template_slots_inspection_fk" }).onDelete("restrict"),
  uniqueIndex("mockup_template_slots_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("mockup_template_slots_key_unique").on(table.tenantId, table.templatePackVersionId, table.slotKey),
  uniqueIndex("mockup_template_slots_ordinal_unique").on(table.tenantId, table.templatePackVersionId, table.ordinal),
]);

export const mockupBatches = pgTable("mockup_batches", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  templatePackVersionId: uuid("template_pack_version_id").notNull(),
  platform: text("platform").notNull(),
  locale: text("locale").notNull(),
  status: text("status").$type<PodBatchStatus>().default("queued").notNull(),
  itemCount: integer("item_count").notNull(),
  completedCount: integer("completed_count").default(0).notNull(),
  failedCount: integer("failed_count").default(0).notNull(),
  requestChecksum: text("request_checksum").notNull(),
  createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("mockup_batches_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("mockup_batches_status_check", sql`${table.status} in ('queued','running','awaiting_review','partially_succeeded','completed','failed','cancelled')`),
  check("mockup_batches_platform_check", sql`${table.platform} in ('amazon','etsy')`),
  check("mockup_batches_locale_check", sql`${table.locale} ~ '^[a-z]{2}-[A-Z]{2}$'`),
  check("mockup_batches_count_check", sql`${table.itemCount} between 1 and 50 and ${table.completedCount} between 0 and ${table.itemCount} and ${table.failedCount} between 0 and ${table.itemCount}`),
  check("mockup_batches_checksum_check", sql`${table.requestChecksum} ~ '^[0-9a-f]{64}$'`),
  foreignKey({ columns: [table.tenantId, table.templatePackVersionId], foreignColumns: [mockupTemplatePackVersions.tenantId, mockupTemplatePackVersions.id], name: "mockup_batches_pack_fk" }).onDelete("restrict"),
  uniqueIndex("mockup_batches_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("mockup_batches_checksum_unique").on(table.tenantId, table.requestChecksum),
  index("mockup_batches_status_idx").on(table.tenantId, table.status, table.updatedAt),
]);

export const mockupBatchItems = pgTable("mockup_batch_items", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  batchId: uuid("batch_id").notNull(),
  ordinal: integer("ordinal").notNull(),
  designVersionId: uuid("design_version_id").notNull(),
  skuId: uuid("sku_id").notNull(),
  status: text("status").$type<PodBatchStatus>().default("queued").notNull(),
  reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { mode: "date", withTimezone: true }),
  rejectionReason: text("rejection_reason"),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
  updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  check("mockup_batch_items_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("mockup_batch_items_ordinal_check", sql`${table.ordinal} between 0 and 49`),
  check("mockup_batch_items_status_check", sql`${table.status} in ('queued','running','awaiting_review','partially_succeeded','completed','failed','cancelled')`),
  check("mockup_batch_items_rejection_check", sql`${table.rejectionReason} is null or length(${table.rejectionReason}) > 0`),
  foreignKey({ columns: [table.tenantId, table.batchId], foreignColumns: [mockupBatches.tenantId, mockupBatches.id], name: "mockup_batch_items_batch_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.designVersionId], foreignColumns: [designVersions.tenantId, designVersions.id], name: "mockup_batch_items_design_version_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.skuId], foreignColumns: [skus.tenantId, skus.id], name: "mockup_batch_items_sku_fk" }).onDelete("restrict"),
  uniqueIndex("mockup_batch_items_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("mockup_batch_items_ordinal_unique").on(table.tenantId, table.batchId, table.ordinal),
  uniqueIndex("mockup_batch_items_pair_unique").on(table.tenantId, table.batchId, table.designVersionId, table.skuId),
  index("mockup_batch_items_status_idx").on(table.tenantId, table.batchId, table.status, table.ordinal),
]);

export const mockupBatchOutputs = pgTable("mockup_batch_outputs", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  itemId: uuid("item_id").notNull(),
  templateSlotId: uuid("template_slot_id").notNull(),
  slotKey: text("slot_key").notNull(),
  attempt: integer("attempt").default(0).notNull(),
  status: text("status").$type<MockupOutputStatus>().default("queued").notNull(),
  assetId: uuid("asset_id"),
  assetVersion: integer("asset_version"),
  checksumSha256: text("checksum_sha256"),
  width: integer("width"),
  height: integer("height"),
  qualitySnapshot: jsonb("quality_snapshot").$type<Record<string, unknown>>(),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date", withTimezone: true }),
}, (table) => [
  check("mockup_batch_outputs_id_uuidv7_check", sql`substring(${table.id}::text from 15 for 1) = '7'`),
  check("mockup_batch_outputs_slot_check", sql`${table.slotKey} ~ '^[a-z][a-z0-9_.-]{0,79}$'`),
  check("mockup_batch_outputs_attempt_check", sql`${table.attempt} between 0 and 20`),
  check("mockup_batch_outputs_status_check", sql`${table.status} in ('queued','running','succeeded','failed','approved','rejected')`),
  check("mockup_batch_outputs_version_check", sql`${table.assetVersion} is null or ${table.assetVersion} > 0`),
  check("mockup_batch_outputs_checksum_check", sql`${table.checksumSha256} is null or ${table.checksumSha256} ~ '^[0-9a-f]{64}$'`),
  check("mockup_batch_outputs_success_check", sql`${table.status} not in ('succeeded','approved','rejected') or (${table.assetId} is not null and ${table.assetVersion} is not null and ${table.checksumSha256} is not null and ${table.width} > 0 and ${table.height} > 0 and ${table.completedAt} is not null)`),
  check("mockup_batch_outputs_failure_check", sql`${table.status} <> 'failed' or (${table.errorCode} is not null and ${table.errorMessage} is not null and ${table.completedAt} is not null)`),
  foreignKey({ columns: [table.tenantId, table.itemId], foreignColumns: [mockupBatchItems.tenantId, mockupBatchItems.id], name: "mockup_batch_outputs_item_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.templateSlotId], foreignColumns: [mockupTemplateSlots.tenantId, mockupTemplateSlots.id], name: "mockup_batch_outputs_slot_fk" }).onDelete("restrict"),
  foreignKey({ columns: [table.tenantId, table.assetId], foreignColumns: [assetFiles.tenantId, assetFiles.id], name: "mockup_batch_outputs_asset_fk" }).onDelete("restrict"),
  uniqueIndex("mockup_batch_outputs_tenant_id_unique").on(table.tenantId, table.id),
  uniqueIndex("mockup_batch_outputs_attempt_unique").on(table.tenantId, table.itemId, table.slotKey, table.attempt),
  index("mockup_batch_outputs_status_idx").on(table.tenantId, table.itemId, table.status, table.slotKey),
]);
