import { expect, test, type Page } from "@playwright/test";
import { createEntityId } from "@yummyai/contracts";
import { CANVAS_BRIDGE, type CanvasBrief, type CanvasResultReceipt } from "@yummyai/contracts/pod/canvas-bridge";
import { apiFetch } from "../src/server-api";
import { syntheticProductionPng } from "./production-editor-fixture";

test("original pinned canvas connects through its public plugin, persists images and returns reviewed ERP results", async ({ page }, testInfo) => {
  test.setTimeout(180_000);
  page.setDefaultTimeout(15_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1600, height: 1100 });
  await page.goto("/navigation");
  const nav = page.getByRole("navigation", { name: "主导航", exact: true });
  await nav.getByRole("button", { name: "创意设计", exact: true }).click();
  await nav.getByRole("link", { name: "创意工作台", exact: true }).click();
  await expect(nav.locator('[aria-current="page"]')).toHaveText("创意工作台");
  const name = `E2E Canvas ${createEntityId().slice(-8)}`;
  await page.getByRole("button", { name: /原创图案.*先选创意方向/ }).click();
  await page.getByRole("textbox", { name: "需求名称", exact: true }).fill(name);
  await page.getByRole("textbox", { name: "创作说明", exact: true }).fill("Synthetic red and blue artwork, no AI provider calls.");
  const saved = page.waitForResponse((response) => response.url().endsWith("/api/canvas-bridge/briefs") && response.request().method() === "POST");
  await page.getByRole("button", { name: "保存创作需求", exact: true }).click();
  const saveResponse = await saved; expect(saveResponse.ok()).toBe(true);
  const brief = await saveResponse.json() as CanvasBrief;
  await expect(page).toHaveURL(new RegExp(`brief=${brief.id}`));
  await page.reload();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  const popupPromise = page.waitForEvent("popup");
  await page.getByRole("button", { name: "打开创意画布", exact: true }).click();
  const canvas = await popupPromise;
  canvas.setDefaultTimeout(15_000);
  canvas.on("pageerror", (error) => errors.push(error.message));
  await canvas.setViewportSize({ width: 1600, height: 1100 });
  await expect(canvas.getByRole("button", { name: CANVAS_BRIDGE.upstreamVersion, exact: true })).toBeVisible();
  await expect(canvas).toHaveURL(/\/canvas\/[^?]+\?mode=recent.*yummyaiChannel=/);
  await canvas.getByRole("button", { name: "节点插件", exact: true }).click();
  await canvas.getByRole("tab", { name: "第三方插件", exact: true }).click();
  const panel = canvas.getByRole("tabpanel", { name: "第三方插件", exact: true });
  await panel.getByRole("textbox").fill(`${new URL(page.url()).origin}/plugins/${CANVAS_BRIDGE.pluginFile}`);
  await panel.getByRole("button", { name: "安装", exact: true }).click();
  await expect(panel.getByText("YummyAI ERP 创作接入", { exact: true })).toBeVisible();
  await canvas.getByRole("button", { name: "Close", exact: true }).click();
  await canvas.getByRole("button", { name: "收起 Agent 面板", exact: true }).click();
  await canvas.getByRole("button", { name: "扩展节点", exact: true }).click();
  await canvas.getByRole("button", { name: "ERP 创作任务", exact: true }).click();
  await canvas.getByRole("button", { name: "读取当前需求", exact: true }).click();
  await expect(canvas.getByRole("heading", { name, exact: true })).toBeVisible();
  await canvas.getByRole("button", { name: "将需求和所选素材加入画布", exact: true }).click();
  await expect(canvas.getByRole("status")).toContainText("已加入");
  await expect(canvas.getByText("1. 创意方案", { exact: true }).first()).toBeVisible();
  await expect(canvas.getByText("2. 精修定稿", { exact: true }).first()).toBeVisible();
  const chooserPromise = canvas.waitForEvent("filechooser");
  await canvas.getByRole("button", { name: "上传资产", exact: true }).click();
  await (await chooserPromise).setFiles({ name: "canvas-synthetic.png", mimeType: "image/png", buffer: syntheticProductionPng() });
  await canvas.getByRole("button", { name: "ERP 创作任务 ERP 创作任务", exact: true }).click();
  await canvas.getByRole("button", { name: "刷新画布图片", exact: true }).click();
  await fillResult(canvas, "canvas-synthetic.png", "Synthetic reviewed master");
  const returned = page.waitForResponse((response) => response.url().endsWith(`/briefs/${brief.id}/results`) && response.request().method() === "POST");
  await canvas.getByRole("button", { name: "提交到 ERP 待审核", exact: true }).click();
  const resultResponse = await returned; expect(resultResponse.ok()).toBe(true);
  const receipt = await resultResponse.json() as CanvasResultReceipt;
  expect(receipt.replayed).toBe(false);
  await expect(canvas.getByRole("status")).toContainText("已保存到 ERP");
  await expect(page.getByRole("heading", { name: "方案与审核 1/4", exact: true })).toBeVisible();

  // Reload the unmodified host: verifies native image persistence and plugin-private retry identity.
  await canvas.reload();
  await canvas.getByRole("button", { name: "ERP 创作任务 ERP 创作任务", exact: true }).click();
  await canvas.getByRole("button", { name: "读取当前需求", exact: true }).click();
  await expect(canvas.getByRole("heading", { name, exact: true })).toBeVisible();
  await canvas.getByRole("button", { name: "刷新画布图片", exact: true }).click();
  await fillResult(canvas, "canvas-synthetic.png", "Synthetic reviewed master");
  const replay = page.waitForResponse((response) => response.url().endsWith(`/briefs/${brief.id}/results`) && response.request().method() === "POST");
  await canvas.getByRole("button", { name: "提交到 ERP 待审核", exact: true }).click();
  const replayed = await (await replay).json() as CanvasResultReceipt;
  expect(replayed).toEqual({ ...receipt, replayed: true });
  await canvas.screenshot({ path: testInfo.outputPath("original-canvas-plugin.png") });

  await expect(page.getByRole("img", { name: "Synthetic reviewed master", exact: true })).toBeVisible();
  await expect.poll(() => page.getByRole("img", { name: "Synthetic reviewed master", exact: true }).evaluate((element) => (element as HTMLImageElement).naturalWidth)).toBe(512);
  await page.getByRole("checkbox", { name: "选择方案 Synthetic reviewed master", exact: true }).check();
  await page.getByRole("button", { name: "批准选中（1）", exact: true }).click();
  await expect(page.locator(".canvas-result .canvas-badge")).toHaveText("已通过");
  await expect(page.getByRole("button", { name: "绑定所选 SKU", exact: true })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("erp-approved-master.png"), fullPage: true });

  // A reviewed result can be selected as an authorized reference in another brief.
  const optionsResponse = await apiFetch(`${process.env.API_BASE_URL}/v1/canvas-bridge/options`);
  expect(optionsResponse.ok).toBe(true);
  const options = await optionsResponse.json() as { referenceAssets: Array<{ id: string; fileName: string }> };
  const approved = options.referenceAssets.find((asset) => asset.id === receipt.assetId)!;
  expect(approved).toBeDefined();
  await page.getByRole("button", { name: "刷新任务", exact: true }).click();
  await expect(page.getByRole("button", { name: "刷新任务", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "新建创作", exact: true }).click();
  await page.getByRole("textbox", { name: "需求名称", exact: true }).fill(`${name} reference`);
  await page.getByRole("textbox", { name: "创作说明", exact: true }).fill("Reuse the approved synthetic image as a reference without AI generation.");
  await page.getByRole("checkbox", { name: approved.fileName, exact: true }).check();
  await page.getByRole("button", { name: "保存创作需求", exact: true }).click();
  await expect(page.getByRole("heading", { name: `${name} reference`, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "打开创意画布", exact: true }).click();
  await canvas.waitForLoadState("domcontentloaded");
  await canvas.getByRole("button", { name: "ERP 创作任务 ERP 创作任务", exact: true }).click();
  await canvas.getByRole("button", { name: "读取当前需求", exact: true }).click();
  await expect(canvas.getByRole("heading", { name: `${name} reference`, exact: true })).toBeVisible();
  await canvas.getByRole("button", { name: "将需求和所选素材加入画布", exact: true }).click();
  await expect(canvas.getByRole("status")).toContainText("已加入");
  await expect(canvas.getByRole("img", { name: approved.fileName, exact: true }).first()).toBeVisible();
  // Batch submission uses one idempotent receipt per image through the real upstream plugin.
  await canvas.getByRole("button", { name: "ERP 创作任务 ERP 创作任务", exact: true }).click();
  await canvas.getByRole("button", { name: "刷新画布图片", exact: true }).click();
  await fillResult(canvas, "canvas-synthetic.png", "Synthetic batch");
  await canvas.getByRole("checkbox", { name: "批量回传图片（最多 4 张，共用来源说明）", exact: true }).check();
  await canvas.getByRole("group", { name: /选择批量方案/ }).getByRole("checkbox", { name: approved.fileName, exact: true }).check();
  await canvas.getByRole("checkbox", { name: "确认图片及参考素材可以用于本次设计" }).check();
  await canvas.getByRole("button", { name: "提交到 ERP 待审核", exact: true }).click();
  await expect(canvas.getByRole("status")).toContainText("已保存到 ERP 2 个方案");
  await expect(page.locator(".canvas-result")).toHaveCount(2);
  await canvas.getByRole("button", { name: "提交到 ERP 待审核", exact: true }).click();
  await expect(canvas.getByRole("status")).toContainText("2 个为重复提交");
  await expect(page.locator(".canvas-result")).toHaveCount(2);
  await page.screenshot({ path: testInfo.outputPath("erp-canvas-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("heading", { name: "创意工作台", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "打开全部导航", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "全部导航", exact: true }).getByRole("link", { name: "创意工作台", exact: true })).toHaveAttribute("aria-current", "page");
  await page.screenshot({ path: testInfo.outputPath("erp-canvas-mobile.png"), fullPage: true });
  expect(errors).toEqual([]);
});

async function fillResult(canvas: Page, image: string, title: string) {
  await canvas.getByRole("combobox", { name: "选择图片", exact: true }).selectOption({ label: image });
  await canvas.getByRole("textbox", { name: "方案名称", exact: true }).fill(title);
  await canvas.getByRole("combobox", { name: "图片来源", exact: true }).selectOption("owned");
  await canvas.getByRole("textbox", { name: "来源说明", exact: true }).fill("Synthetic fixture generated by the ERP test suite.");
  await canvas.getByRole("checkbox", { name: "确认图片及参考素材可以用于本次设计" }).check();
}
