export const Permission = {
  AssetPromote: "asset:promote",
  AssetRead: "asset:read",
  AssetWrite: "asset:write",
  CaptureRead: "capture:read",
  CaptureWrite: "capture:write",
  ChannelInventoryRead: "channel_inventory:read",
  ChannelInventoryReconcile: "channel_inventory:reconcile",
  ChannelInventoryWrite: "channel_inventory:write",
  DashboardRead: "dashboard:read",
  DesignRead: "design:read",
  DesignReview: "design:review",
  DesignWrite: "design:write",
  FinanceRead: "finance:read",
  FinanceReview: "finance:review",
  FinanceWrite: "finance:write",
  InventoryRead: "inventory:read",
  InventoryWrite: "inventory:write",
  ListingRead: "listing:read",
  ListingReview: "listing:review",
  ListingWrite: "listing:write",
  ListingPublish: "listing:publish",
  JobRead: "job:read",
  MembershipManage: "membership:manage",
  ModelConfigure: "model:configure",
  NotificationRead: "notification:read",
  OrderPiiRead: "order:pii:read",
  OrderPiiAnonymize: "order:pii:anonymize",
  OrderRead: "order:read",
  OrderWrite: "order:write",
  ProductRead: "product:read",
  ProductWrite: "product:write",
  ProcurementApprove: "procurement:approve",
  ProcurementRead: "procurement:read",
  ProcurementWrite: "procurement:write",
  ResearchRead: "research:read",
  ResearchWrite: "research:write",
  StoreAuthorize: "store:authorize",
  StoreManage: "store:manage",
  StoreRead: "store:read",
  SupplierPerformanceRead: "supplier_performance:read",
  SupplierPerformanceReview: "supplier_performance:review",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
