export const DATABASE_CONNECTION = Symbol("DATABASE_CONNECTION");
export const PRIVATE_STORAGE = Symbol("PRIVATE_STORAGE");
export const CAPTURE_MEDIA_ENQUEUER = Symbol("CAPTURE_MEDIA_ENQUEUER");
export const MODEL_SECRET_VAULT = Symbol("MODEL_SECRET_VAULT");
export const ANALYSIS_JOB_ENQUEUER = Symbol("ANALYSIS_JOB_ENQUEUER");
