export const DATABASE_CONNECTION = Symbol("DATABASE_CONNECTION");
export const PRIVATE_STORAGE = Symbol("PRIVATE_STORAGE");
export const CAPTURE_MEDIA_ENQUEUER = Symbol("CAPTURE_MEDIA_ENQUEUER");
export const MODEL_SECRET_VAULT = Symbol("MODEL_SECRET_VAULT");
export const ANALYSIS_JOB_ENQUEUER = Symbol("ANALYSIS_JOB_ENQUEUER");
export const CATALOG_REPOSITORY = Symbol("CATALOG_REPOSITORY");
export const SUPPLIER_REPOSITORY = Symbol("SUPPLIER_REPOSITORY");
export const DESIGN_REPOSITORY = Symbol("DESIGN_REPOSITORY");
